/* tslint:disable */
/* eslint-disable */
/**
 * Authorization Permissions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Permission } from './Permission';
import {
    PermissionFromJSON,
    PermissionFromJSONTyped,
    PermissionToJSON,
    PermissionToJSONTyped,
} from './Permission';

/**
 * 
 * @export
 * @interface CreateResponse
 */
export interface CreateResponse {
    /**
     * 
     * @type {Permission}
     * @memberof CreateResponse
     */
    permission: Permission;
}

/**
 * Check if a given object implements the CreateResponse interface.
 */
export function instanceOfCreateResponse(value: object): value is CreateResponse {
    if (!('permission' in value) || value['permission'] === undefined) return false;
    return true;
}

export function CreateResponseFromJSON(json: any): CreateResponse {
    return CreateResponseFromJSONTyped(json, false);
}

export function CreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'permission': PermissionFromJSON(json['permission']),
    };
}

export function CreateResponseToJSON(json: any): CreateResponse {
    return CreateResponseToJSONTyped(json, false);
}

export function CreateResponseToJSONTyped(value?: CreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'permission': PermissionToJSON(value['permission']),
    };
}

