/* tslint:disable */
/* eslint-disable */
/**
 * Authorization Permissions
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListMyPermissions200Response
 */
export interface ListMyPermissions200Response {
    /**
     * 
     * @type {Array<string>}
     * @memberof ListMyPermissions200Response
     */
    permissions: Array<string>;
}

/**
 * Check if a given object implements the ListMyPermissions200Response interface.
 */
export function instanceOfListMyPermissions200Response(value: object): value is ListMyPermissions200Response {
    if (!('permissions' in value) || value['permissions'] === undefined) return false;
    return true;
}

export function ListMyPermissions200ResponseFromJSON(json: any): ListMyPermissions200Response {
    return ListMyPermissions200ResponseFromJSONTyped(json, false);
}

export function ListMyPermissions200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListMyPermissions200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'permissions': json['permissions'],
    };
}

export function ListMyPermissions200ResponseToJSON(json: any): ListMyPermissions200Response {
    return ListMyPermissions200ResponseToJSONTyped(json, false);
}

export function ListMyPermissions200ResponseToJSONTyped(value?: ListMyPermissions200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'permissions': value['permissions'],
    };
}

