/* tslint:disable */
/* eslint-disable */
/**
 * Role Bindings API
 * Manages assignments of roles to users.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AssignRoleRequest,
  ErrorResponse,
  RoleBinding,
  UnassignRoleRequest,
} from '../models/index';
import {
    AssignRoleRequestFromJSON,
    AssignRoleRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    RoleBindingFromJSON,
    RoleBindingToJSON,
    UnassignRoleRequestFromJSON,
    UnassignRoleRequestToJSON,
} from '../models/index';

export interface AssignRoleOperationRequest {
    assignRoleRequest: AssignRoleRequest;
}

export interface GetAllRoleBindingsRequest {
    page?: number;
    pageSize?: number;
}

export interface GetRolebindingsForUserRequest {
    userID: string;
}

export interface UnassignRoleOperationRequest {
    unassignRoleRequest: UnassignRoleRequest;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Creates role bindings between the specified users and roles.
     * Assign roles to users
     */
    async assignRoleRaw(requestParameters: AssignRoleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['assignRoleRequest'] == null) {
            throw new runtime.RequiredError(
                'assignRoleRequest',
                'Required parameter "assignRoleRequest" was null or undefined when calling assignRole().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/role_bindings`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AssignRoleRequestToJSON(requestParameters['assignRoleRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Creates role bindings between the specified users and roles.
     * Assign roles to users
     */
    async assignRole(requestParameters: AssignRoleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.assignRoleRaw(requestParameters, initOverrides);
    }

    /**
     * Returns a paginated list of all role bindings in the system.
     * List all role bindings
     */
    async getAllRoleBindingsRaw(requestParameters: GetAllRoleBindingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RoleBinding>>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/role_bindings`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RoleBindingFromJSON));
    }

    /**
     * Returns a paginated list of all role bindings in the system.
     * List all role bindings
     */
    async getAllRoleBindings(requestParameters: GetAllRoleBindingsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RoleBinding>> {
        const response = await this.getAllRoleBindingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns all role assignments for the specified user.
     * Get all role bindings for a user
     */
    async getRolebindingsForUserRaw(requestParameters: GetRolebindingsForUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<RoleBinding>>> {
        if (requestParameters['userID'] == null) {
            throw new runtime.RequiredError(
                'userID',
                'Required parameter "userID" was null or undefined when calling getRolebindingsForUser().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/role_bindings/{userID}`;
        urlPath = urlPath.replace(`{${"userID"}}`, encodeURIComponent(String(requestParameters['userID'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RoleBindingFromJSON));
    }

    /**
     * Returns all role assignments for the specified user.
     * Get all role bindings for a user
     */
    async getRolebindingsForUser(requestParameters: GetRolebindingsForUserRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RoleBinding>> {
        const response = await this.getRolebindingsForUserRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Removes role bindings between the specified users and roles.
     * Remove role assignments from users
     */
    async unassignRoleRaw(requestParameters: UnassignRoleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['unassignRoleRequest'] == null) {
            throw new runtime.RequiredError(
                'unassignRoleRequest',
                'Required parameter "unassignRoleRequest" was null or undefined when calling unassignRole().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/role_bindings`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: UnassignRoleRequestToJSON(requestParameters['unassignRoleRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes role bindings between the specified users and roles.
     * Remove role assignments from users
     */
    async unassignRole(requestParameters: UnassignRoleOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.unassignRoleRaw(requestParameters, initOverrides);
    }

}
