// Code generated by MockGen. DO NOT EDIT.
// Source: factory.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	aggsv1 "github.com/ooqls/go-auth/internal/aggsv1"
	permissionbindingsv1 "github.com/ooqls/go-auth/internal/permissionbindingsv1"
	permissionsv1 "github.com/ooqls/go-auth/internal/permissionsv1"
	resourcesv1 "github.com/ooqls/go-auth/internal/resourcesv1"
	rolebindingsv1 "github.com/ooqls/go-auth/internal/rolebindingsv1"
	rolesv1 "github.com/ooqls/go-auth/internal/rolesv1"
	usersv1 "github.com/ooqls/go-auth/internal/usersv1"
)

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// NewAggReader mocks base method.
func (m *MockFactory) NewAggReader() aggsv1.Reader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewAggReader")
	ret0, _ := ret[0].(aggsv1.Reader)
	return ret0
}

// NewAggReader indicates an expected call of NewAggReader.
func (mr *MockFactoryMockRecorder) NewAggReader() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewAggReader", reflect.TypeOf((*MockFactory)(nil).NewAggReader))
}

// NewPermissionBindingReader mocks base method.
func (m *MockFactory) NewPermissionBindingReader() permissionbindingsv1.Reader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewPermissionBindingReader")
	ret0, _ := ret[0].(permissionbindingsv1.Reader)
	return ret0
}

// NewPermissionBindingReader indicates an expected call of NewPermissionBindingReader.
func (mr *MockFactoryMockRecorder) NewPermissionBindingReader() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewPermissionBindingReader", reflect.TypeOf((*MockFactory)(nil).NewPermissionBindingReader))
}

// NewPermissionBindingWriter mocks base method.
func (m *MockFactory) NewPermissionBindingWriter() permissionbindingsv1.Writer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewPermissionBindingWriter")
	ret0, _ := ret[0].(permissionbindingsv1.Writer)
	return ret0
}

// NewPermissionBindingWriter indicates an expected call of NewPermissionBindingWriter.
func (mr *MockFactoryMockRecorder) NewPermissionBindingWriter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewPermissionBindingWriter", reflect.TypeOf((*MockFactory)(nil).NewPermissionBindingWriter))
}

// NewPermissionReader mocks base method.
func (m *MockFactory) NewPermissionReader() permissionsv1.Reader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewPermissionReader")
	ret0, _ := ret[0].(permissionsv1.Reader)
	return ret0
}

// NewPermissionReader indicates an expected call of NewPermissionReader.
func (mr *MockFactoryMockRecorder) NewPermissionReader() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewPermissionReader", reflect.TypeOf((*MockFactory)(nil).NewPermissionReader))
}

// NewPermissionWriter mocks base method.
func (m *MockFactory) NewPermissionWriter() permissionsv1.Writer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewPermissionWriter")
	ret0, _ := ret[0].(permissionsv1.Writer)
	return ret0
}

// NewPermissionWriter indicates an expected call of NewPermissionWriter.
func (mr *MockFactoryMockRecorder) NewPermissionWriter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewPermissionWriter", reflect.TypeOf((*MockFactory)(nil).NewPermissionWriter))
}

// NewResourceReader mocks base method.
func (m *MockFactory) NewResourceReader() resourcesv1.Reader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewResourceReader")
	ret0, _ := ret[0].(resourcesv1.Reader)
	return ret0
}

// NewResourceReader indicates an expected call of NewResourceReader.
func (mr *MockFactoryMockRecorder) NewResourceReader() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewResourceReader", reflect.TypeOf((*MockFactory)(nil).NewResourceReader))
}

// NewResourceWriter mocks base method.
func (m *MockFactory) NewResourceWriter() resourcesv1.Writer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewResourceWriter")
	ret0, _ := ret[0].(resourcesv1.Writer)
	return ret0
}

// NewResourceWriter indicates an expected call of NewResourceWriter.
func (mr *MockFactoryMockRecorder) NewResourceWriter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewResourceWriter", reflect.TypeOf((*MockFactory)(nil).NewResourceWriter))
}

// NewRoleBindingsReader mocks base method.
func (m *MockFactory) NewRoleBindingsReader() rolebindingsv1.Reader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewRoleBindingsReader")
	ret0, _ := ret[0].(rolebindingsv1.Reader)
	return ret0
}

// NewRoleBindingsReader indicates an expected call of NewRoleBindingsReader.
func (mr *MockFactoryMockRecorder) NewRoleBindingsReader() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRoleBindingsReader", reflect.TypeOf((*MockFactory)(nil).NewRoleBindingsReader))
}

// NewRoleBindingsWriter mocks base method.
func (m *MockFactory) NewRoleBindingsWriter() rolebindingsv1.Writer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewRoleBindingsWriter")
	ret0, _ := ret[0].(rolebindingsv1.Writer)
	return ret0
}

// NewRoleBindingsWriter indicates an expected call of NewRoleBindingsWriter.
func (mr *MockFactoryMockRecorder) NewRoleBindingsWriter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRoleBindingsWriter", reflect.TypeOf((*MockFactory)(nil).NewRoleBindingsWriter))
}

// NewRoleReader mocks base method.
func (m *MockFactory) NewRoleReader() rolesv1.Reader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewRoleReader")
	ret0, _ := ret[0].(rolesv1.Reader)
	return ret0
}

// NewRoleReader indicates an expected call of NewRoleReader.
func (mr *MockFactoryMockRecorder) NewRoleReader() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRoleReader", reflect.TypeOf((*MockFactory)(nil).NewRoleReader))
}

// NewRoleWriter mocks base method.
func (m *MockFactory) NewRoleWriter() rolesv1.Writer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewRoleWriter")
	ret0, _ := ret[0].(rolesv1.Writer)
	return ret0
}

// NewRoleWriter indicates an expected call of NewRoleWriter.
func (mr *MockFactoryMockRecorder) NewRoleWriter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRoleWriter", reflect.TypeOf((*MockFactory)(nil).NewRoleWriter))
}

// NewUserReader mocks base method.
func (m *MockFactory) NewUserReader() usersv1.Reader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewUserReader")
	ret0, _ := ret[0].(usersv1.Reader)
	return ret0
}

// NewUserReader indicates an expected call of NewUserReader.
func (mr *MockFactoryMockRecorder) NewUserReader() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewUserReader", reflect.TypeOf((*MockFactory)(nil).NewUserReader))
}

// NewUserWriter mocks base method.
func (m *MockFactory) NewUserWriter() usersv1.Writer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewUserWriter")
	ret0, _ := ret[0].(usersv1.Writer)
	return ret0
}

// NewUserWriter indicates an expected call of NewUserWriter.
func (mr *MockFactoryMockRecorder) NewUserWriter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewUserWriter", reflect.TypeOf((*MockFactory)(nil).NewUserWriter))
}
