// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role_bindings.query.sql

package datagen

import (
	"context"

	"github.com/google/uuid"
)

const addRoleToUser = `-- name: AddRoleToUser :exec
INSERT INTO rolebindingsv1 (user_id, role_id) VALUES ($1, $2)
`

type AddRoleToUserParams struct {
	UserID uuid.UUID
	RoleID uuid.UUID
}

func (q *Queries) AddRoleToUser(ctx context.Context, arg AddRoleToUserParams) error {
	_, err := q.db.Exec(ctx, addRoleToUser, arg.UserID, arg.RoleID)
	return err
}

const getRoleBindingsForUser = `-- name: GetRoleBindingsForUser :many
SELECT user_id, role_id, created_at, updated_at FROM rolebindingsv1 WHERE user_id = $1
`

func (q *Queries) GetRoleBindingsForUser(ctx context.Context, userID uuid.UUID) ([]Rolebindingsv1, error) {
	rows, err := q.db.Query(ctx, getRoleBindingsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rolebindingsv1
	for rows.Next() {
		var i Rolebindingsv1
		if err := rows.Scan(
			&i.UserID,
			&i.RoleID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoleFromUser = `-- name: RemoveRoleFromUser :exec
DELETE FROM rolebindingsv1 WHERE user_id = $1 AND role_id = $2
`

type RemoveRoleFromUserParams struct {
	UserID uuid.UUID
	RoleID uuid.UUID
}

func (q *Queries) RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error {
	_, err := q.db.Exec(ctx, removeRoleFromUser, arg.UserID, arg.RoleID)
	return err
}

const userHasRole = `-- name: UserHasRole :one
SELECT EXISTS(SELECT 1 FROM rolebindingsv1 WHERE user_id = $1 AND role_id = $2)
`

type UserHasRoleParams struct {
	UserID uuid.UUID
	RoleID uuid.UUID
}

func (q *Queries) UserHasRole(ctx context.Context, arg UserHasRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, userHasRole, arg.UserID, arg.RoleID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
