// Package gen_permissionbindings provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package gen_permissionbindings

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// AssignRequest defines model for AssignRequest.
type AssignRequest struct {
	PermissionIds []openapi_types.UUID `json:"permission_ids"`
	RoleIds       []openapi_types.UUID `json:"role_ids"`
}

// PermissionBinding defines model for PermissionBinding.
type PermissionBinding struct {
	PermissionId openapi_types.UUID `json:"permission_id"`
	RoleId       openapi_types.UUID `json:"role_id"`
}

// UnassignRequest defines model for UnassignRequest.
type UnassignRequest struct {
	PermissionIds []openapi_types.UUID `json:"permission_ids"`
	RoleIds       []openapi_types.UUID `json:"role_ids"`
}

// ListPermissionBindingsParams defines parameters for ListPermissionBindings.
type ListPermissionBindingsParams struct {
	// Page The page number
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize The page size
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// UnassignPermissionJSONRequestBody defines body for UnassignPermission for application/json ContentType.
type UnassignPermissionJSONRequestBody = UnassignRequest

// AssignPermissionJSONRequestBody defines body for AssignPermission for application/json ContentType.
type AssignPermissionJSONRequestBody = AssignRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// UnassignPermissionWithBody request with any body
	UnassignPermissionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UnassignPermission(ctx context.Context, body UnassignPermissionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListPermissionBindings request
	ListPermissionBindings(ctx context.Context, params *ListPermissionBindingsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AssignPermissionWithBody request with any body
	AssignPermissionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AssignPermission(ctx context.Context, body AssignPermissionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPermissionBindingsForRole request
	GetPermissionBindingsForRole(ctx context.Context, roleId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) UnassignPermissionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUnassignPermissionRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UnassignPermission(ctx context.Context, body UnassignPermissionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUnassignPermissionRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListPermissionBindings(ctx context.Context, params *ListPermissionBindingsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListPermissionBindingsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AssignPermissionWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAssignPermissionRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AssignPermission(ctx context.Context, body AssignPermissionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAssignPermissionRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPermissionBindingsForRole(ctx context.Context, roleId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPermissionBindingsForRoleRequest(c.Server, roleId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewUnassignPermissionRequest calls the generic UnassignPermission builder with application/json body
func NewUnassignPermissionRequest(server string, body UnassignPermissionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUnassignPermissionRequestWithBody(server, "application/json", bodyReader)
}

// NewUnassignPermissionRequestWithBody generates requests for UnassignPermission with any type of body
func NewUnassignPermissionRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/permission-binding")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListPermissionBindingsRequest generates requests for ListPermissionBindings
func NewListPermissionBindingsRequest(server string, params *ListPermissionBindingsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/permission-binding")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page", runtime.ParamLocationQuery, *params.Page); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page_size", runtime.ParamLocationQuery, *params.PageSize); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAssignPermissionRequest calls the generic AssignPermission builder with application/json body
func NewAssignPermissionRequest(server string, body AssignPermissionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAssignPermissionRequestWithBody(server, "application/json", bodyReader)
}

// NewAssignPermissionRequestWithBody generates requests for AssignPermission with any type of body
func NewAssignPermissionRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/permission-binding")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetPermissionBindingsForRoleRequest generates requests for GetPermissionBindingsForRole
func NewGetPermissionBindingsForRoleRequest(server string, roleId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "role_id", runtime.ParamLocationPath, roleId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/permission-binding/role/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// UnassignPermissionWithBodyWithResponse request with any body
	UnassignPermissionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UnassignPermissionResponse, error)

	UnassignPermissionWithResponse(ctx context.Context, body UnassignPermissionJSONRequestBody, reqEditors ...RequestEditorFn) (*UnassignPermissionResponse, error)

	// ListPermissionBindingsWithResponse request
	ListPermissionBindingsWithResponse(ctx context.Context, params *ListPermissionBindingsParams, reqEditors ...RequestEditorFn) (*ListPermissionBindingsResponse, error)

	// AssignPermissionWithBodyWithResponse request with any body
	AssignPermissionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AssignPermissionResponse, error)

	AssignPermissionWithResponse(ctx context.Context, body AssignPermissionJSONRequestBody, reqEditors ...RequestEditorFn) (*AssignPermissionResponse, error)

	// GetPermissionBindingsForRoleWithResponse request
	GetPermissionBindingsForRoleWithResponse(ctx context.Context, roleId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetPermissionBindingsForRoleResponse, error)
}

type UnassignPermissionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r UnassignPermissionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UnassignPermissionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListPermissionBindingsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]PermissionBinding
}

// Status returns HTTPResponse.Status
func (r ListPermissionBindingsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListPermissionBindingsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AssignPermissionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r AssignPermissionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AssignPermissionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetPermissionBindingsForRoleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]PermissionBinding
}

// Status returns HTTPResponse.Status
func (r GetPermissionBindingsForRoleResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPermissionBindingsForRoleResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// UnassignPermissionWithBodyWithResponse request with arbitrary body returning *UnassignPermissionResponse
func (c *ClientWithResponses) UnassignPermissionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UnassignPermissionResponse, error) {
	rsp, err := c.UnassignPermissionWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUnassignPermissionResponse(rsp)
}

func (c *ClientWithResponses) UnassignPermissionWithResponse(ctx context.Context, body UnassignPermissionJSONRequestBody, reqEditors ...RequestEditorFn) (*UnassignPermissionResponse, error) {
	rsp, err := c.UnassignPermission(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUnassignPermissionResponse(rsp)
}

// ListPermissionBindingsWithResponse request returning *ListPermissionBindingsResponse
func (c *ClientWithResponses) ListPermissionBindingsWithResponse(ctx context.Context, params *ListPermissionBindingsParams, reqEditors ...RequestEditorFn) (*ListPermissionBindingsResponse, error) {
	rsp, err := c.ListPermissionBindings(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListPermissionBindingsResponse(rsp)
}

// AssignPermissionWithBodyWithResponse request with arbitrary body returning *AssignPermissionResponse
func (c *ClientWithResponses) AssignPermissionWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AssignPermissionResponse, error) {
	rsp, err := c.AssignPermissionWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAssignPermissionResponse(rsp)
}

func (c *ClientWithResponses) AssignPermissionWithResponse(ctx context.Context, body AssignPermissionJSONRequestBody, reqEditors ...RequestEditorFn) (*AssignPermissionResponse, error) {
	rsp, err := c.AssignPermission(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAssignPermissionResponse(rsp)
}

// GetPermissionBindingsForRoleWithResponse request returning *GetPermissionBindingsForRoleResponse
func (c *ClientWithResponses) GetPermissionBindingsForRoleWithResponse(ctx context.Context, roleId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetPermissionBindingsForRoleResponse, error) {
	rsp, err := c.GetPermissionBindingsForRole(ctx, roleId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPermissionBindingsForRoleResponse(rsp)
}

// ParseUnassignPermissionResponse parses an HTTP response from a UnassignPermissionWithResponse call
func ParseUnassignPermissionResponse(rsp *http.Response) (*UnassignPermissionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UnassignPermissionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseListPermissionBindingsResponse parses an HTTP response from a ListPermissionBindingsWithResponse call
func ParseListPermissionBindingsResponse(rsp *http.Response) (*ListPermissionBindingsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListPermissionBindingsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []PermissionBinding
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseAssignPermissionResponse parses an HTTP response from a AssignPermissionWithResponse call
func ParseAssignPermissionResponse(rsp *http.Response) (*AssignPermissionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AssignPermissionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetPermissionBindingsForRoleResponse parses an HTTP response from a GetPermissionBindingsForRoleWithResponse call
func ParseGetPermissionBindingsForRoleResponse(rsp *http.Response) (*GetPermissionBindingsForRoleResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPermissionBindingsForRoleResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []PermissionBinding
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Unassign permissions from roles
	// (DELETE /auth/permission-binding)
	UnassignPermission(c *gin.Context)
	// Retrieves all permission bindings
	// (GET /auth/permission-binding)
	ListPermissionBindings(c *gin.Context, params ListPermissionBindingsParams)
	// Assign permissions to roles
	// (POST /auth/permission-binding)
	AssignPermission(c *gin.Context)
	// Retrieves all permission bindings for a specific role
	// (GET /auth/permission-binding/role/{role_id})
	GetPermissionBindingsForRole(c *gin.Context, roleId openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// UnassignPermission operation middleware
func (siw *ServerInterfaceWrapper) UnassignPermission(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UnassignPermission(c)
}

// ListPermissionBindings operation middleware
func (siw *ServerInterfaceWrapper) ListPermissionBindings(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPermissionBindingsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page_size: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListPermissionBindings(c, params)
}

// AssignPermission operation middleware
func (siw *ServerInterfaceWrapper) AssignPermission(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AssignPermission(c)
}

// GetPermissionBindingsForRole operation middleware
func (siw *ServerInterfaceWrapper) GetPermissionBindingsForRole(c *gin.Context) {

	var err error

	// ------------- Path parameter "role_id" -------------
	var roleId openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "role_id", c.Param("role_id"), &roleId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter role_id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPermissionBindingsForRole(c, roleId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.DELETE(options.BaseURL+"/auth/permission-binding", wrapper.UnassignPermission)
	router.GET(options.BaseURL+"/auth/permission-binding", wrapper.ListPermissionBindings)
	router.POST(options.BaseURL+"/auth/permission-binding", wrapper.AssignPermission)
	router.GET(options.BaseURL+"/auth/permission-binding/role/:role_id", wrapper.GetPermissionBindingsForRole)
}
