openapi: 3.0.0
info:
  title: Authorization Resources
  version: 1.0.0
components:
  schemas:
    CreateResourceRequest:
      type: object
      required:
      - resource
      properties:
        resource:
          $ref: "schemas.yaml#/components/schemas/Resource"
    CreateResourceResponse:
      type: object
      required:
        - resource
      properties:
        resource:
          $ref: "schemas.yaml#/components/schemas/Resource"
paths:
  /auth/resource:
    get:
      responses:
        '200':
          description: Successful resource retrieval
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "schemas.yaml#/components/schemas/Resource"
        '401':
          description: Invalid credentials
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateResourceRequest"
        required: true
      responses:
        '200':
          description: Successful resource creation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateResourceResponse"
        '401':
          description: Invalid credentials
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "schemas.yaml#/components/schemas/UpdateRequest"
      responses:
        '200':
          description: Successful resource update
          content:
            application/json:
              schema:
                $ref: "schemas.yaml#/components/schemas/Resource"
        '401':
          description: Invalid credentials
    delete:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "schemas.yaml#/components/schemas/DeleteRequest"
      responses:
        '200':
          description: Successful resource deletion
          content:
            application/json:
              schema:
                $ref: "schemas.yaml#/components/schemas/DeleteResponse"
        '401':
          description: Invalid credentials