// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package datagen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Challengeattemptsv1 struct {
	ID          uuid.UUID
	ChallengeID uuid.UUID
	UserID      uuid.UUID
	Success     bool
	CreatedAt   pgtype.Timestamptz
}

type Challengesv1 struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Challenge string
	Salt      []byte
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

type Permissionbindingsv1 struct {
	RoleID       uuid.UUID
	PermissionID uuid.UUID
}

type Permissionsv1 struct {
	ID         uuid.UUID
	Permission string
}

type Resourcesv1 struct {
	ID          uuid.UUID
	Name        string
	Rgroup      string
	Kind        string
	Description string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Rolebindingsv1 struct {
	UserID    uuid.UUID
	RoleID    uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Rolesv1 struct {
	ID          uuid.UUID
	Name        string
	Hierarchy   int32
	Description string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type UserHighestRole struct {
	UserID    uuid.UUID
	RoleID    uuid.UUID
	RoleName  string
	Hierarchy int32
}

type Usersv1 struct {
	ID        uuid.UUID
	Username  string
	Email     string
	Key       []byte
	Salt      []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
