// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resources.query.sql

package datagen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createResource = `-- name: CreateResource :one
INSERT INTO resourcesv1 (
  resource_kind,
  resource_group,
  resource_name,
  description,
  created_at,
  updated_at,
  id
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
) RETURNING id, resource_group, resource_kind, resource_name, description, created_at, updated_at
`

type CreateResourceParams struct {
	ResourceKind  string
	ResourceGroup string
	ResourceName  string
	Description   string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	ID            uuid.UUID
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resourcesv1, error) {
	row := q.db.QueryRow(ctx, createResource,
		arg.ResourceKind,
		arg.ResourceGroup,
		arg.ResourceName,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Resourcesv1
	err := row.Scan(
		&i.ID,
		&i.ResourceGroup,
		&i.ResourceKind,
		&i.ResourceName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteResource = `-- name: DeleteResource :exec
DELETE FROM resourcesv1 WHERE resource_name = $1 AND resource_group = $2 AND resource_kind = $3
`

type DeleteResourceParams struct {
	ResourceName  string
	ResourceGroup string
	ResourceKind  string
}

func (q *Queries) DeleteResource(ctx context.Context, arg DeleteResourceParams) error {
	_, err := q.db.Exec(ctx, deleteResource, arg.ResourceName, arg.ResourceGroup, arg.ResourceKind)
	return err
}

const deleteResourceById = `-- name: DeleteResourceById :exec
DELETE FROM resourcesv1 WHERE id = $1
`

func (q *Queries) DeleteResourceById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteResourceById, id)
	return err
}

const getResourceByID = `-- name: GetResourceByID :one
SELECT id, resource_group, resource_kind, resource_name, description, created_at, updated_at FROM resourcesv1 WHERE id = $1
`

func (q *Queries) GetResourceByID(ctx context.Context, id uuid.UUID) (Resourcesv1, error) {
	row := q.db.QueryRow(ctx, getResourceByID, id)
	var i Resourcesv1
	err := row.Scan(
		&i.ID,
		&i.ResourceGroup,
		&i.ResourceKind,
		&i.ResourceName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResourceByName = `-- name: GetResourceByName :one
SELECT id, resource_group, resource_kind, resource_name, description, created_at, updated_at FROM resourcesv1 WHERE resource_name = $1 AND resource_group = $2 AND resource_kind = $3
`

type GetResourceByNameParams struct {
	ResourceName  string
	ResourceGroup string
	ResourceKind  string
}

func (q *Queries) GetResourceByName(ctx context.Context, arg GetResourceByNameParams) (Resourcesv1, error) {
	row := q.db.QueryRow(ctx, getResourceByName, arg.ResourceName, arg.ResourceGroup, arg.ResourceKind)
	var i Resourcesv1
	err := row.Scan(
		&i.ID,
		&i.ResourceGroup,
		&i.ResourceKind,
		&i.ResourceName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResources = `-- name: GetResources :many
SELECT id, resource_group, resource_kind, resource_name, description, created_at, updated_at FROM resourcesv1 WHERE resource_group = $1 AND ($2::text = '*' OR resource_kind = $2) ORDER BY resource_name LIMIT $3 OFFSET $4
`

type GetResourcesParams struct {
	ResourceGroup string
	Column2       string
	Limit         int32
	Offset        int32
}

func (q *Queries) GetResources(ctx context.Context, arg GetResourcesParams) ([]Resourcesv1, error) {
	rows, err := q.db.Query(ctx, getResources,
		arg.ResourceGroup,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resourcesv1
	for rows.Next() {
		var i Resourcesv1
		if err := rows.Scan(
			&i.ID,
			&i.ResourceGroup,
			&i.ResourceKind,
			&i.ResourceName,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResource = `-- name: UpdateResource :one
UPDATE resourcesv1 SET
  resource_name = COALESCE(NULLIF($1, ''), resource_name),
  description = COALESCE(NULLIF($2, ''), description),
  updated_at = now()
WHERE id = $3
RETURNING id, resource_group, resource_kind, resource_name, description, created_at, updated_at
`

type UpdateResourceParams struct {
	Name        interface{}
	Description interface{}
	ID          uuid.UUID
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resourcesv1, error) {
	row := q.db.QueryRow(ctx, updateResource, arg.Name, arg.Description, arg.ID)
	var i Resourcesv1
	err := row.Scan(
		&i.ID,
		&i.ResourceGroup,
		&i.ResourceKind,
		&i.ResourceName,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
