// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resources.query.sql

package datagen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAllResources = `-- name: CountAllResources :one
SELECT COUNT(*) FROM resourcesv1
`

func (q *Queries) CountAllResources(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllResources)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countResources = `-- name: CountResources :one
SELECT COUNT(*) FROM resourcesv1 WHERE rGroup = $1 AND kind = $2
`

type CountResourcesParams struct {
	Rgroup string
	Kind   string
}

func (q *Queries) CountResources(ctx context.Context, arg CountResourcesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countResources, arg.Rgroup, arg.Kind)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countResourcesByGroup = `-- name: CountResourcesByGroup :one
SELECT COUNT(*) FROM resourcesv1 WHERE rGroup = $1
`

func (q *Queries) CountResourcesByGroup(ctx context.Context, rgroup string) (int64, error) {
	row := q.db.QueryRow(ctx, countResourcesByGroup, rgroup)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createResource = `-- name: CreateResource :one
INSERT INTO resourcesv1 (
  name,
  rGroup,
  kind,
  created_at,
  updated_at,
  id
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
) RETURNING id, name, rgroup, kind, description, created_at, updated_at
`

type CreateResourceParams struct {
	Name      string
	Rgroup    string
	Kind      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	ID        uuid.UUID
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resourcesv1, error) {
	row := q.db.QueryRow(ctx, createResource,
		arg.Name,
		arg.Rgroup,
		arg.Kind,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Resourcesv1
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Rgroup,
		&i.Kind,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteResource = `-- name: DeleteResource :exec
DELETE FROM resourcesv1 WHERE name = $1 and rGroup = $2 and kind = $3
`

type DeleteResourceParams struct {
	Name   string
	Rgroup string
	Kind   string
}

func (q *Queries) DeleteResource(ctx context.Context, arg DeleteResourceParams) error {
	_, err := q.db.Exec(ctx, deleteResource, arg.Name, arg.Rgroup, arg.Kind)
	return err
}

const deleteResourceById = `-- name: DeleteResourceById :exec
DELETE FROM resourcesv1 WHERE id = $1
`

func (q *Queries) DeleteResourceById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteResourceById, id)
	return err
}

const getResourceByID = `-- name: GetResourceByID :one
SELECT id, name, rgroup, kind, description, created_at, updated_at FROM resourcesv1 WHERE id = $1
`

func (q *Queries) GetResourceByID(ctx context.Context, id uuid.UUID) (Resourcesv1, error) {
	row := q.db.QueryRow(ctx, getResourceByID, id)
	var i Resourcesv1
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Rgroup,
		&i.Kind,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResourceByName = `-- name: GetResourceByName :one
SELECT id, name, rgroup, kind, description, created_at, updated_at FROM resourcesv1 WHERE name = $1
`

func (q *Queries) GetResourceByName(ctx context.Context, name string) (Resourcesv1, error) {
	row := q.db.QueryRow(ctx, getResourceByName, name)
	var i Resourcesv1
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Rgroup,
		&i.Kind,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResources = `-- name: GetResources :many
SELECT id, name, rgroup, kind, description, created_at, updated_at FROM resourcesv1 ORDER BY name LIMIT $1 OFFSET $2
`

type GetResourcesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetResources(ctx context.Context, arg GetResourcesParams) ([]Resourcesv1, error) {
	rows, err := q.db.Query(ctx, getResources, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resourcesv1
	for rows.Next() {
		var i Resourcesv1
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Rgroup,
			&i.Kind,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResourcesByGroup = `-- name: GetResourcesByGroup :many
SELECT id, name, rgroup, kind, description, created_at, updated_at FROM resourcesv1 WHERE rGroup = $1 ORDER BY name LIMIT $2 OFFSET $3
`

type GetResourcesByGroupParams struct {
	Rgroup string
	Limit  int32
	Offset int32
}

func (q *Queries) GetResourcesByGroup(ctx context.Context, arg GetResourcesByGroupParams) ([]Resourcesv1, error) {
	rows, err := q.db.Query(ctx, getResourcesByGroup, arg.Rgroup, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resourcesv1
	for rows.Next() {
		var i Resourcesv1
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Rgroup,
			&i.Kind,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResourcesByGroupAndKind = `-- name: GetResourcesByGroupAndKind :many
SELECT id, name, rgroup, kind, description, created_at, updated_at FROM resourcesv1 WHERE rGroup = $1 AND kind = $2 ORDER BY name LIMIT $3 OFFSET $4
`

type GetResourcesByGroupAndKindParams struct {
	Rgroup string
	Kind   string
	Limit  int32
	Offset int32
}

func (q *Queries) GetResourcesByGroupAndKind(ctx context.Context, arg GetResourcesByGroupAndKindParams) ([]Resourcesv1, error) {
	rows, err := q.db.Query(ctx, getResourcesByGroupAndKind,
		arg.Rgroup,
		arg.Kind,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resourcesv1
	for rows.Next() {
		var i Resourcesv1
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Rgroup,
			&i.Kind,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchResources = `-- name: SearchResources :many
SELECT id, name, rgroup, kind, description, created_at, updated_at FROM resourcesv1
WHERE (rGroup = $1 OR $1 IS NULL)
  AND (kind = $2 OR $2 IS NULL)
  AND (name = $3 OR $3 IS NULL)
  AND ($4::text IS NULL OR name ILIKE '%' || $4 || '%')
ORDER BY name
LIMIT $5 OFFSET $6
`

type SearchResourcesParams struct {
	Rgroup pgtype.Text
	Kind   pgtype.Text
	Name   pgtype.Text
	Query  pgtype.Text
	Limit  int32
	Offset int32
}

func (q *Queries) SearchResources(ctx context.Context, arg SearchResourcesParams) ([]Resourcesv1, error) {
	rows, err := q.db.Query(ctx, searchResources,
		arg.Rgroup,
		arg.Kind,
		arg.Name,
		arg.Query,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resourcesv1
	for rows.Next() {
		var i Resourcesv1
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Rgroup,
			&i.Kind,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSearchResources = `-- name: CountSearchResources :one
SELECT COUNT(*) FROM resourcesv1
WHERE (rGroup = $1 OR $1 IS NULL)
  AND (kind = $2 OR $2 IS NULL)
  AND (name = $3 OR $3 IS NULL)
  AND ($4::text IS NULL OR name ILIKE '%' || $4 || '%')
`

type CountSearchResourcesParams struct {
	Rgroup pgtype.Text
	Kind   pgtype.Text
	Name   pgtype.Text
	Query  pgtype.Text
}

func (q *Queries) CountSearchResources(ctx context.Context, arg CountSearchResourcesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchResources,
		arg.Rgroup,
		arg.Kind,
		arg.Name,
		arg.Query,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateResource = `-- name: UpdateResource :one
UPDATE resourcesv1 SET
  name = $4,
  updated_at = now()
WHERE rGroup = $1 AND kind = $2 AND name = $3
RETURNING id, name, rgroup, kind, description, created_at, updated_at
`

type UpdateResourceParams struct {
	Rgroup string
	Kind   string
	Name   string
	Name_2 string
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resourcesv1, error) {
	row := q.db.QueryRow(ctx, updateResource,
		arg.Rgroup,
		arg.Kind,
		arg.Name,
		arg.Name_2,
	)
	var i Resourcesv1
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Rgroup,
		&i.Kind,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
