/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI specification for auth
 * This is the OpenAPI specification for the auth service.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthenticateResponse,
  ChallengeClientResponse,
  ChallengeServerResponse,
  ErrorResponse,
  LoginChallengeRequest,
  RefreshRequest,
  RegistrationRequest,
  RegistrationResponse,
  VerifyKeyRequest,
  VerifyKeyResp,
} from '../models/index';
import {
    AuthenticateResponseFromJSON,
    AuthenticateResponseToJSON,
    ChallengeClientResponseFromJSON,
    ChallengeClientResponseToJSON,
    ChallengeServerResponseFromJSON,
    ChallengeServerResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    LoginChallengeRequestFromJSON,
    LoginChallengeRequestToJSON,
    RefreshRequestFromJSON,
    RefreshRequestToJSON,
    RegistrationRequestFromJSON,
    RegistrationRequestToJSON,
    RegistrationResponseFromJSON,
    RegistrationResponseToJSON,
    VerifyKeyRequestFromJSON,
    VerifyKeyRequestToJSON,
    VerifyKeyRespFromJSON,
    VerifyKeyRespToJSON,
} from '../models/index';

export interface LoginChallengeOperationRequest {
    loginChallengeRequest: LoginChallengeRequest;
}

export interface LoginChallengeResponseRequest {
    challengeClientResponse: ChallengeClientResponse;
}

export interface RefreshTokenRequest {
    refreshRequest: RefreshRequest;
}

export interface RegisterRequest {
    registrationRequest: RegistrationRequest;
}

export interface VerifyKeyOperationRequest {
    verifyKeyRequest: VerifyKeyRequest;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * tests if the user is authed
     * tests if the user is authed
     */
    async isAuthedRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthenticateResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/authed`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthenticateResponseFromJSON(jsonValue));
    }

    /**
     * tests if the user is authed
     * tests if the user is authed
     */
    async isAuthed(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthenticateResponse> {
        const response = await this.isAuthedRaw(initOverrides);
        return await response.value();
    }

    /**
     * Requests a challenge from the server to login
     * Requests a challenge from the server to login
     */
    async loginChallengeRaw(requestParameters: LoginChallengeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChallengeServerResponse>> {
        if (requestParameters['loginChallengeRequest'] == null) {
            throw new runtime.RequiredError(
                'loginChallengeRequest',
                'Required parameter "loginChallengeRequest" was null or undefined when calling loginChallenge().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/login_challenge`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LoginChallengeRequestToJSON(requestParameters['loginChallengeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChallengeServerResponseFromJSON(jsonValue));
    }

    /**
     * Requests a challenge from the server to login
     * Requests a challenge from the server to login
     */
    async loginChallenge(requestParameters: LoginChallengeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChallengeServerResponse> {
        const response = await this.loginChallengeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Answers the login question
     * Answers the login question
     */
    async loginChallengeResponseRaw(requestParameters: LoginChallengeResponseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['challengeClientResponse'] == null) {
            throw new runtime.RequiredError(
                'challengeClientResponse',
                'Required parameter "challengeClientResponse" was null or undefined when calling loginChallengeResponse().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/login_challenge_response`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChallengeClientResponseToJSON(requestParameters['challengeClientResponse']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Answers the login question
     * Answers the login question
     */
    async loginChallengeResponse(requestParameters: LoginChallengeResponseRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.loginChallengeResponseRaw(requestParameters, initOverrides);
    }

    /**
     * Logs out the user
     * Logs out the user
     */
    async logoutRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/logout`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Logs out the user
     * Logs out the user
     */
    async logout(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.logoutRaw(initOverrides);
    }

    /**
     * Refresh the authentication token
     * Refresh token
     */
    async refreshTokenRaw(requestParameters: RefreshTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['refreshRequest'] == null) {
            throw new runtime.RequiredError(
                'refreshRequest',
                'Required parameter "refreshRequest" was null or undefined when calling refreshToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/refresh`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RefreshRequestToJSON(requestParameters['refreshRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Refresh the authentication token
     * Refresh token
     */
    async refreshToken(requestParameters: RefreshTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.refreshTokenRaw(requestParameters, initOverrides);
    }

    /**
     * Starts a new user registration
     * Starts a new user registration
     */
    async registerRaw(requestParameters: RegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegistrationResponse>> {
        if (requestParameters['registrationRequest'] == null) {
            throw new runtime.RequiredError(
                'registrationRequest',
                'Required parameter "registrationRequest" was null or undefined when calling register().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/registration`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegistrationRequestToJSON(requestParameters['registrationRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegistrationResponseFromJSON(jsonValue));
    }

    /**
     * Starts a new user registration
     * Starts a new user registration
     */
    async register(requestParameters: RegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegistrationResponse> {
        const response = await this.registerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * verify the given key
     * verify the given key
     */
    async verifyKeyRaw(requestParameters: VerifyKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VerifyKeyResp>> {
        if (requestParameters['verifyKeyRequest'] == null) {
            throw new runtime.RequiredError(
                'verifyKeyRequest',
                'Required parameter "verifyKeyRequest" was null or undefined when calling verifyKey().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/verify`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifyKeyRequestToJSON(requestParameters['verifyKeyRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VerifyKeyRespFromJSON(jsonValue));
    }

    /**
     * verify the given key
     * verify the given key
     */
    async verifyKey(requestParameters: VerifyKeyOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VerifyKeyResp> {
        const response = await this.verifyKeyRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
