/* tslint:disable */
/* eslint-disable */
/**
 * Role Bindings API
 * Manages assignments of roles to users.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for assigning one or more roles to one or more users.
 * @export
 * @interface AssignRoleRequest
 */
export interface AssignRoleRequest {
    /**
     * The UUIDs of the users to assign roles to.
     * @type {Array<string>}
     * @memberof AssignRoleRequest
     */
    userIDs: Array<string>;
    /**
     * The UUIDs of the roles to assign.
     * @type {Array<string>}
     * @memberof AssignRoleRequest
     */
    roleIDs: Array<string>;
}

/**
 * Check if a given object implements the AssignRoleRequest interface.
 */
export function instanceOfAssignRoleRequest(value: object): value is AssignRoleRequest {
    if (!('userIDs' in value) || value['userIDs'] === undefined) return false;
    if (!('roleIDs' in value) || value['roleIDs'] === undefined) return false;
    return true;
}

export function AssignRoleRequestFromJSON(json: any): AssignRoleRequest {
    return AssignRoleRequestFromJSONTyped(json, false);
}

export function AssignRoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssignRoleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userIDs': json['userIDs'],
        'roleIDs': json['roleIDs'],
    };
}

export function AssignRoleRequestToJSON(json: any): AssignRoleRequest {
    return AssignRoleRequestToJSONTyped(json, false);
}

export function AssignRoleRequestToJSONTyped(value?: AssignRoleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userIDs': value['userIDs'],
        'roleIDs': value['roleIDs'],
    };
}

