/* tslint:disable */
/* eslint-disable */
/**
 * Role Bindings API
 * Manages assignments of roles to users.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Represents an assignment of a role to a user.
 * @export
 * @interface RoleBinding
 */
export interface RoleBinding {
    /**
     * The UUID of the assigned role.
     * @type {string}
     * @memberof RoleBinding
     */
    roleID?: string;
    /**
     * The UUID of the user the role is assigned to.
     * @type {string}
     * @memberof RoleBinding
     */
    userID?: string;
    /**
     * Timestamp when the binding was created.
     * @type {Date}
     * @memberof RoleBinding
     */
    createdAt?: Date;
    /**
     * Timestamp when the binding was last updated.
     * @type {Date}
     * @memberof RoleBinding
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the RoleBinding interface.
 */
export function instanceOfRoleBinding(value: object): value is RoleBinding {
    return true;
}

export function RoleBindingFromJSON(json: any): RoleBinding {
    return RoleBindingFromJSONTyped(json, false);
}

export function RoleBindingFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleBinding {
    if (json == null) {
        return json;
    }
    return {
        
        'roleID': json['roleID'] == null ? undefined : json['roleID'],
        'userID': json['userID'] == null ? undefined : json['userID'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function RoleBindingToJSON(json: any): RoleBinding {
    return RoleBindingToJSONTyped(json, false);
}

export function RoleBindingToJSONTyped(value?: RoleBinding | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'roleID': value['roleID'],
        'userID': value['userID'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updated_at': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

