/* tslint:disable */
/* eslint-disable */
/**
 * Role Bindings API
 * Manages assignments of roles to users.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for removing one or more role assignments from one or more users.
 * @export
 * @interface UnassignRoleRequest
 */
export interface UnassignRoleRequest {
    /**
     * The UUIDs of the users to remove role assignments from.
     * @type {Array<string>}
     * @memberof UnassignRoleRequest
     */
    userIDs: Array<string>;
    /**
     * The UUIDs of the roles to remove.
     * @type {Array<string>}
     * @memberof UnassignRoleRequest
     */
    roleIDs: Array<string>;
}

/**
 * Check if a given object implements the UnassignRoleRequest interface.
 */
export function instanceOfUnassignRoleRequest(value: object): value is UnassignRoleRequest {
    if (!('userIDs' in value) || value['userIDs'] === undefined) return false;
    if (!('roleIDs' in value) || value['roleIDs'] === undefined) return false;
    return true;
}

export function UnassignRoleRequestFromJSON(json: any): UnassignRoleRequest {
    return UnassignRoleRequestFromJSONTyped(json, false);
}

export function UnassignRoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnassignRoleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userIDs': json['userIDs'],
        'roleIDs': json['roleIDs'],
    };
}

export function UnassignRoleRequestToJSON(json: any): UnassignRoleRequest {
    return UnassignRoleRequestToJSONTyped(json, false);
}

export function UnassignRoleRequestToJSONTyped(value?: UnassignRoleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userIDs': value['userIDs'],
        'roleIDs': value['roleIDs'],
    };
}

