// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permissionbindings.query.sql

package datagen

import (
	"context"

	"github.com/google/uuid"
)

const assignPermission = `-- name: AssignPermission :exec
WITH upserted_permission AS (
  INSERT INTO permissionsv1 (permission)
  VALUES ($1)
  ON CONFLICT (permission) DO UPDATE
    SET permission = EXCLUDED.permission
)
INSERT INTO permissionbindingsv1 (role_id, permission)
VALUES ($2, $1)
ON CONFLICT (role_id, permission) DO NOTHING
`

type AssignPermissionParams struct {
	Permission string
	RoleID     uuid.UUID
}

func (q *Queries) AssignPermission(ctx context.Context, arg AssignPermissionParams) error {
	_, err := q.db.Exec(ctx, assignPermission, arg.Permission, arg.RoleID)
	return err
}

const getPermissions = `-- name: GetPermissions :many
SELECT role_id, permission FROM permissionbindingsv1 LIMIT $1 OFFSET $2
`

type GetPermissionsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetPermissions(ctx context.Context, arg GetPermissionsParams) ([]Permissionbindingsv1, error) {
	rows, err := q.db.Query(ctx, getPermissions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permissionbindingsv1
	for rows.Next() {
		var i Permissionbindingsv1
		if err := rows.Scan(&i.RoleID, &i.Permission); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermissionsForRole = `-- name: GetPermissionsForRole :many
SELECT role_id, permission FROM permissionbindingsv1 WHERE role_id = $1
`

func (q *Queries) GetPermissionsForRole(ctx context.Context, roleID uuid.UUID) ([]Permissionbindingsv1, error) {
	rows, err := q.db.Query(ctx, getPermissionsForRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permissionbindingsv1
	for rows.Next() {
		var i Permissionbindingsv1
		if err := rows.Scan(&i.RoleID, &i.Permission); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unassignAllPermissions = `-- name: UnassignAllPermissions :exec
DELETE FROM permissionbindingsv1 WHERE role_id = $1
`

func (q *Queries) UnassignAllPermissions(ctx context.Context, roleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, unassignAllPermissions, roleID)
	return err
}

const unassignFromAllRoles = `-- name: UnassignFromAllRoles :exec
DELETE FROM permissionbindingsv1 WHERE permission = $1
`

func (q *Queries) UnassignFromAllRoles(ctx context.Context, permission string) error {
	_, err := q.db.Exec(ctx, unassignFromAllRoles, permission)
	return err
}

const unassignPermission = `-- name: UnassignPermission :exec
DELETE FROM permissionbindingsv1 WHERE permission = $1 AND role_id = $2
`

type UnassignPermissionParams struct {
	Permission string
	RoleID     uuid.UUID
}

func (q *Queries) UnassignPermission(ctx context.Context, arg UnassignPermissionParams) error {
	_, err := q.db.Exec(ctx, unassignPermission, arg.Permission, arg.RoleID)
	return err
}
