// Code generated by MockGen. DO NOT EDIT.
// Source: reader.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	contexts "github.com/ooqls/go-auth/internal/contexts"
	permissionbindingsv1 "github.com/ooqls/go-auth/internal/permissionbindingsv1"
)

// MockReader is a mock of Reader interface.
type MockReader struct {
	ctrl     *gomock.Controller
	recorder *MockReaderMockRecorder
}

// MockReaderMockRecorder is the mock recorder for MockReader.
type MockReaderMockRecorder struct {
	mock *MockReader
}

// NewMockReader creates a new mock instance.
func NewMockReader(ctrl *gomock.Controller) *MockReader {
	mock := &MockReader{ctrl: ctrl}
	mock.recorder = &MockReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReader) EXPECT() *MockReaderMockRecorder {
	return m.recorder
}

// GetPermissionBindingsForRole mocks base method.
func (m *MockReader) GetPermissionBindingsForRole(ctx contexts.LContext, roleId uuid.UUID) ([]permissionbindingsv1.Permissionbindingv1, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermissionBindingsForRole", ctx, roleId)
	ret0, _ := ret[0].([]permissionbindingsv1.Permissionbindingv1)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermissionBindingsForRole indicates an expected call of GetPermissionBindingsForRole.
func (mr *MockReaderMockRecorder) GetPermissionBindingsForRole(ctx, roleId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissionBindingsForRole", reflect.TypeOf((*MockReader)(nil).GetPermissionBindingsForRole), ctx, roleId)
}

// GetPermissionsBindings mocks base method.
func (m *MockReader) GetPermissionsBindings(ctx contexts.LContext, page, pageSize int) ([]permissionbindingsv1.Permissionbindingv1, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermissionsBindings", ctx, page, pageSize)
	ret0, _ := ret[0].([]permissionbindingsv1.Permissionbindingv1)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermissionsBindings indicates an expected call of GetPermissionsBindings.
func (mr *MockReaderMockRecorder) GetPermissionsBindings(ctx, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissionsBindings", reflect.TypeOf((*MockReader)(nil).GetPermissionsBindings), ctx, page, pageSize)
}
