// Code generated by MockGen. DO NOT EDIT.
// Source: writer.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	contexts "github.com/ooqls/go-auth/internal/contexts"
)

// MockWriter is a mock of Writer interface.
type MockWriter struct {
	ctrl     *gomock.Controller
	recorder *MockWriterMockRecorder
}

// MockWriterMockRecorder is the mock recorder for MockWriter.
type MockWriterMockRecorder struct {
	mock *MockWriter
}

// NewMockWriter creates a new mock instance.
func NewMockWriter(ctrl *gomock.Controller) *MockWriter {
	mock := &MockWriter{ctrl: ctrl}
	mock.recorder = &MockWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriter) EXPECT() *MockWriterMockRecorder {
	return m.recorder
}

// AssignPermission mocks base method.
func (m *MockWriter) AssignPermission(ctx contexts.LContext, roleID, permissionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignPermission", ctx, roleID, permissionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignPermission indicates an expected call of AssignPermission.
func (mr *MockWriterMockRecorder) AssignPermission(ctx, roleID, permissionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignPermission", reflect.TypeOf((*MockWriter)(nil).AssignPermission), ctx, roleID, permissionID)
}

// UnassignAllPermissions mocks base method.
func (m *MockWriter) UnassignAllPermissions(ctx contexts.LContext, roleID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnassignAllPermissions", ctx, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnassignAllPermissions indicates an expected call of UnassignAllPermissions.
func (mr *MockWriterMockRecorder) UnassignAllPermissions(ctx, roleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnassignAllPermissions", reflect.TypeOf((*MockWriter)(nil).UnassignAllPermissions), ctx, roleID)
}

// UnassignPermission mocks base method.
func (m *MockWriter) UnassignPermission(ctx contexts.LContext, roleID, permissionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnassignPermission", ctx, roleID, permissionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnassignPermission indicates an expected call of UnassignPermission.
func (mr *MockWriterMockRecorder) UnassignPermission(ctx, roleID, permissionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnassignPermission", reflect.TypeOf((*MockWriter)(nil).UnassignPermission), ctx, roleID, permissionID)
}

// UnassignPermissionFromAllRoles mocks base method.
func (m *MockWriter) UnassignPermissionFromAllRoles(ctx contexts.LContext, permissionID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnassignPermissionFromAllRoles", ctx, permissionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnassignPermissionFromAllRoles indicates an expected call of UnassignPermissionFromAllRoles.
func (mr *MockWriterMockRecorder) UnassignPermissionFromAllRoles(ctx, permissionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnassignPermissionFromAllRoles", reflect.TypeOf((*MockWriter)(nil).UnassignPermissionFromAllRoles), ctx, permissionID)
}
