// Code generated by MockGen. DO NOT EDIT.
// Source: authorizer.go
//
// Generated by this command:
//
//	mockgen -source=authorizer.go -destination=mocks/mock_authorizer.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	authorizationv1 "github.com/ooqls/go-auth/internal/authorizationv1"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthorizer is a mock of Authorizer interface.
type MockAuthorizer struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizerMockRecorder
	isgomock struct{}
}

// MockAuthorizerMockRecorder is the mock recorder for MockAuthorizer.
type MockAuthorizerMockRecorder struct {
	mock *MockAuthorizer
}

// NewMockAuthorizer creates a new mock instance.
func NewMockAuthorizer(ctrl *gomock.Controller) *MockAuthorizer {
	mock := &MockAuthorizer{ctrl: ctrl}
	mock.recorder = &MockAuthorizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorizer) EXPECT() *MockAuthorizerMockRecorder {
	return m.recorder
}

// HasHigherHierarchy mocks base method.
func (m *MockAuthorizer) HasHigherHierarchy(ctx *authorizationv1.Context, hierarchy int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasHigherHierarchy", ctx, hierarchy)
	ret0, _ := ret[0].(error)
	return ret0
}

// HasHigherHierarchy indicates an expected call of HasHigherHierarchy.
func (mr *MockAuthorizerMockRecorder) HasHigherHierarchy(ctx, hierarchy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasHigherHierarchy", reflect.TypeOf((*MockAuthorizer)(nil).HasHigherHierarchy), ctx, hierarchy)
}

// IsAuthorizedToAssignPermission mocks base method.
func (m *MockAuthorizer) IsAuthorizedToAssignPermission(ctx *authorizationv1.Context, roleID uuid.UUID, permission string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAuthorizedToAssignPermission", ctx, roleID, permission)
	ret0, _ := ret[0].(error)
	return ret0
}

// IsAuthorizedToAssignPermission indicates an expected call of IsAuthorizedToAssignPermission.
func (mr *MockAuthorizerMockRecorder) IsAuthorizedToAssignPermission(ctx, roleID, permission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAuthorizedToAssignPermission", reflect.TypeOf((*MockAuthorizer)(nil).IsAuthorizedToAssignPermission), ctx, roleID, permission)
}

// IsAuthorizedToModifyUser mocks base method.
func (m *MockAuthorizer) IsAuthorizedToModifyUser(ctx *authorizationv1.Context, targetUserID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAuthorizedToModifyUser", ctx, targetUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IsAuthorizedToModifyUser indicates an expected call of IsAuthorizedToModifyUser.
func (mr *MockAuthorizerMockRecorder) IsAuthorizedToModifyUser(ctx, targetUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAuthorizedToModifyUser", reflect.TypeOf((*MockAuthorizer)(nil).IsAuthorizedToModifyUser), ctx, targetUserID)
}

// IsAuthorizedToPerformCoreAction mocks base method.
func (m *MockAuthorizer) IsAuthorizedToPerformCoreAction(ctx *authorizationv1.Context, action authorizationv1.Action, group, kind string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAuthorizedToPerformCoreAction", ctx, action, group, kind)
	ret0, _ := ret[0].(error)
	return ret0
}

// IsAuthorizedToPerformCoreAction indicates an expected call of IsAuthorizedToPerformCoreAction.
func (mr *MockAuthorizerMockRecorder) IsAuthorizedToPerformCoreAction(ctx, action, group, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAuthorizedToPerformCoreAction", reflect.TypeOf((*MockAuthorizer)(nil).IsAuthorizedToPerformCoreAction), ctx, action, group, kind)
}

// IsAuthorizedToPerformResourceAction mocks base method.
func (m *MockAuthorizer) IsAuthorizedToPerformResourceAction(ctx *authorizationv1.Context, action authorizationv1.Action, group, kind string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAuthorizedToPerformResourceAction", ctx, action, group, kind)
	ret0, _ := ret[0].(error)
	return ret0
}

// IsAuthorizedToPerformResourceAction indicates an expected call of IsAuthorizedToPerformResourceAction.
func (mr *MockAuthorizerMockRecorder) IsAuthorizedToPerformResourceAction(ctx, action, group, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAuthorizedToPerformResourceAction", reflect.TypeOf((*MockAuthorizer)(nil).IsAuthorizedToPerformResourceAction), ctx, action, group, kind)
}

// IsAuthorizedToReadRolePermissions mocks base method.
func (m *MockAuthorizer) IsAuthorizedToReadRolePermissions(ctx *authorizationv1.Context, roleID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAuthorizedToReadRolePermissions", ctx, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IsAuthorizedToReadRolePermissions indicates an expected call of IsAuthorizedToReadRolePermissions.
func (mr *MockAuthorizerMockRecorder) IsAuthorizedToReadRolePermissions(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAuthorizedToReadRolePermissions", reflect.TypeOf((*MockAuthorizer)(nil).IsAuthorizedToReadRolePermissions), ctx, roleID)
}

// IsAuthorizedToReadUserRoles mocks base method.
func (m *MockAuthorizer) IsAuthorizedToReadUserRoles(ctx *authorizationv1.Context, targetUserID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAuthorizedToReadUserRoles", ctx, targetUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IsAuthorizedToReadUserRoles indicates an expected call of IsAuthorizedToReadUserRoles.
func (mr *MockAuthorizerMockRecorder) IsAuthorizedToReadUserRoles(ctx, targetUserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAuthorizedToReadUserRoles", reflect.TypeOf((*MockAuthorizer)(nil).IsAuthorizedToReadUserRoles), ctx, targetUserID)
}

// IsAuthorizedToUnassignPermission mocks base method.
func (m *MockAuthorizer) IsAuthorizedToUnassignPermission(ctx *authorizationv1.Context, roleID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAuthorizedToUnassignPermission", ctx, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IsAuthorizedToUnassignPermission indicates an expected call of IsAuthorizedToUnassignPermission.
func (mr *MockAuthorizerMockRecorder) IsAuthorizedToUnassignPermission(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAuthorizedToUnassignPermission", reflect.TypeOf((*MockAuthorizer)(nil).IsAuthorizedToUnassignPermission), ctx, roleID)
}
