// Code generated by MockGen. DO NOT EDIT.
// Source: authorizer.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	authorizationv1 "github.com/ooqls/go-auth/internal/authorizationv1"
)

// MockAuthorizer is a mock of Authorizer interface.
type MockAuthorizer struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizerMockRecorder
}

// MockAuthorizerMockRecorder is the mock recorder for MockAuthorizer.
type MockAuthorizerMockRecorder struct {
	mock *MockAuthorizer
}

// NewMockAuthorizer creates a new mock instance.
func NewMockAuthorizer(ctrl *gomock.Controller) *MockAuthorizer {
	mock := &MockAuthorizer{ctrl: ctrl}
	mock.recorder = &MockAuthorizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorizer) EXPECT() *MockAuthorizerMockRecorder {
	return m.recorder
}

// IsAuthorizedToAssignPermission mocks base method.
func (m *MockAuthorizer) IsAuthorizedToAssignPermission(ctx *authorizationv1.Context, roleID uuid.UUID, permission string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAuthorizedToAssignPermission", ctx, roleID, permission)
	ret0, _ := ret[0].(error)
	return ret0
}

// IsAuthorizedToAssignPermission indicates an expected call of IsAuthorizedToAssignPermission.
func (mr *MockAuthorizerMockRecorder) IsAuthorizedToAssignPermission(ctx, roleID, permission interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAuthorizedToAssignPermission", reflect.TypeOf((*MockAuthorizer)(nil).IsAuthorizedToAssignPermission), ctx, roleID, permission)
}

// IsAuthorizedToModifyUser mocks base method.
func (m *MockAuthorizer) IsAuthorizedToModifyUser(ctx *authorizationv1.Context, targetUserID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAuthorizedToModifyUser", ctx, targetUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IsAuthorizedToModifyUser indicates an expected call of IsAuthorizedToModifyUser.
func (mr *MockAuthorizerMockRecorder) IsAuthorizedToModifyUser(ctx, targetUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAuthorizedToModifyUser", reflect.TypeOf((*MockAuthorizer)(nil).IsAuthorizedToModifyUser), ctx, targetUserID)
}

// IsAuthorizedToPerformAction mocks base method.
func (m *MockAuthorizer) IsAuthorizedToPerformAction(ctx *authorizationv1.Context, action authorizationv1.Action, target string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAuthorizedToPerformAction", ctx, action, target)
	ret0, _ := ret[0].(error)
	return ret0
}

// IsAuthorizedToPerformAction indicates an expected call of IsAuthorizedToPerformAction.
func (mr *MockAuthorizerMockRecorder) IsAuthorizedToPerformAction(ctx, action, target interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAuthorizedToPerformAction", reflect.TypeOf((*MockAuthorizer)(nil).IsAuthorizedToPerformAction), ctx, action, target)
}

// IsAuthorizedToReadRolePermissions mocks base method.
func (m *MockAuthorizer) IsAuthorizedToReadRolePermissions(ctx *authorizationv1.Context, roleID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAuthorizedToReadRolePermissions", ctx, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IsAuthorizedToReadRolePermissions indicates an expected call of IsAuthorizedToReadRolePermissions.
func (mr *MockAuthorizerMockRecorder) IsAuthorizedToReadRolePermissions(ctx, roleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAuthorizedToReadRolePermissions", reflect.TypeOf((*MockAuthorizer)(nil).IsAuthorizedToReadRolePermissions), ctx, roleID)
}

// IsAuthorizedToReadUserRoles mocks base method.
func (m *MockAuthorizer) IsAuthorizedToReadUserRoles(ctx *authorizationv1.Context, targetUserID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAuthorizedToReadUserRoles", ctx, targetUserID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IsAuthorizedToReadUserRoles indicates an expected call of IsAuthorizedToReadUserRoles.
func (mr *MockAuthorizerMockRecorder) IsAuthorizedToReadUserRoles(ctx, targetUserID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAuthorizedToReadUserRoles", reflect.TypeOf((*MockAuthorizer)(nil).IsAuthorizedToReadUserRoles), ctx, targetUserID)
}

// IsAuthorizedToUnassignPermission mocks base method.
func (m *MockAuthorizer) IsAuthorizedToUnassignPermission(ctx *authorizationv1.Context, roleID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAuthorizedToUnassignPermission", ctx, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// IsAuthorizedToUnassignPermission indicates an expected call of IsAuthorizedToUnassignPermission.
func (mr *MockAuthorizerMockRecorder) IsAuthorizedToUnassignPermission(ctx, roleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAuthorizedToUnassignPermission", reflect.TypeOf((*MockAuthorizer)(nil).IsAuthorizedToUnassignPermission), ctx, roleID)
}
