apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "go-auth.fullname" . }}-registry
  labels:
    {{- include "go-auth.labels" . | nindent 4 }}
data:
  registry.yaml: |
    postgres:
      name: postgres
      host: {{ include "go-auth.postgresHost" . }}
      port: {{ .Values.postgres.port }}
      database: {{ .Values.postgres.database }}
      auth:
        enabled: true
        username: {{ .Values.postgres.auth.username }}
        password_file: /run/secrets/db/postgres-password
      {{- if .Values.tls.enabled }}
      tls:
        enabled: true
        ca_path: /config/tls/ca.crt
        cert_path: /config/tls/server.crt
        key_path: /config/tls/server.key
        insecure_skip_tls_verify: false
      {{- end }}
    valkeys:
      name: valkey
      host: {{ include "go-auth.valkeyHost" . }}
      port: {{ .Values.valkey.port }}
      database: {{ .Values.valkey.database | quote }}
      auth:
        enabled: {{ .Values.valkey.auth.enabled }}
        password_file: /run/secrets/db/valkey-password
      {{- if .Values.tls.enabled }}
      tls:
        enabled: true
        ca_path: /config/tls/ca.crt
        cert_path: /config/tls/server.crt
        key_path: /config/tls/server.key
        insecure_skip_tls_verify: false
      {{- end }}
