{{- if and .Values.tls.enabled (eq .Values.tls.mode "secret") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "go-auth.fullname" . }}-tls
  labels:
    {{- include "go-auth.labels" . | nindent 4 }}
type: Opaque
data:
  ca.crt: {{ .Files.Get "files/ca.crt" | b64enc | quote }}
  server.crt: {{ .Files.Get "files/server.crt" | b64enc | quote }}
  server.key: {{ .Files.Get "files/server.key" | b64enc | quote }}
{{- end }}
