apiVersion: v1
kind: Secret
metadata:
  name: {{ include "go-auth.fullname" . }}-db-passwords
  labels:
    {{- include "go-auth.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ required "postgres.auth.password is required" .Values.postgres.auth.password | quote }}
  valkey-password: {{ required "valkey.auth.password is required" .Values.valkey.auth.password | quote }}
