apiVersion: v1
kind: Secret
metadata:
  name: {{ include "go-auth.fullname" . }}-jwt
  labels:
    {{- include "go-auth.labels" . | nindent 4 }}
type: Opaque
data:
  jwt.key: {{ .Files.Get "files/jwt.key" | b64enc | quote }}
  jwt.pub: {{ .Files.Get "files/jwt.pub" | b64enc | quote }}
