// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.query.sql

package datagen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRole = `-- name: CreateRole :one
INSERT INTO rolesv1 (
  name,
  description,
  hierarchy
) VALUES (
  $1,
  $2,
  $3
) RETURNING id, name, hierarchy, description, created_at, updated_at
`

type CreateRoleParams struct {
	Name        string
	Description string
	Hierarchy   int32
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Rolesv1, error) {
	row := q.db.QueryRow(ctx, createRole, arg.Name, arg.Description, arg.Hierarchy)
	var i Rolesv1
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hierarchy,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM rolesv1 WHERE id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRole, id)
	return err
}

const getRole = `-- name: GetRole :one
SELECT id, name, hierarchy, description, created_at, updated_at FROM rolesv1 WHERE id = $1
`

func (q *Queries) GetRole(ctx context.Context, id uuid.UUID) (Rolesv1, error) {
	row := q.db.QueryRow(ctx, getRole, id)
	var i Rolesv1
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hierarchy,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoles = `-- name: GetRoles :many
SELECT id, name, hierarchy, description, created_at, updated_at FROM rolesv1 ORDER BY name LIMIT $1 OFFSET $2
`

type GetRolesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetRoles(ctx context.Context, arg GetRolesParams) ([]Rolesv1, error) {
	rows, err := q.db.Query(ctx, getRoles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Rolesv1
	for rows.Next() {
		var i Rolesv1
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hierarchy,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRolesByName = `-- name: GetRolesByName :one
SELECT id, name, hierarchy, description, created_at, updated_at FROM rolesv1 WHERE name = $1 ORDER BY name LIMIT 1
`

func (q *Queries) GetRolesByName(ctx context.Context, name string) (Rolesv1, error) {
	row := q.db.QueryRow(ctx, getRolesByName, name)
	var i Rolesv1
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hierarchy,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRole = `-- name: UpdateRole :one
UPDATE rolesv1 SET
  name = COALESCE($2, name),
  description = COALESCE($3, description),
  hierarchy = COALESCE($4, hierarchy)
WHERE id = $1
RETURNING id, name, hierarchy, description, created_at, updated_at
`

type UpdateRoleParams struct {
	ID          uuid.UUID
	Name        pgtype.Text
	Description pgtype.Text
	Hierarchy   pgtype.Int4
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Rolesv1, error) {
	row := q.db.QueryRow(ctx, updateRole,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Hierarchy,
	)
	var i Rolesv1
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hierarchy,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
