openapi: 3.0.0
info:
  title: Authorization Users
  version: 1.0.0
components:
  schemas:
    CreateUserRequest:
      type: object
      required:
      - user
      properties:
        user:
          $ref: "schemas.yaml#/components/schemas/User"
    CreateUserResponse:
      type: object
      required:
        - user
      properties:
        user:
          $ref: "schemas.yaml#/components/schemas/User"
paths:
  /auth/user:
    get:
      responses:
        '200':
          description: Successful user retrieval
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "schemas.yaml#/components/schemas/User"
        '401':
          description: Invalid credentials
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUserRequest"
        required: true
      responses:
        '200':
          description: Successful user creation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateUserResponse"
        '401':
          description: Invalid credentials
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "schemas.yaml#/components/schemas/UpdateRequest"
      responses:
        '200':
          description: Successful user update
          content:
            application/json:
              schema:
                $ref: "schemas.yaml#/components/schemas/User"
        '401':
          description: Invalid credentials
    delete:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "schemas.yaml#/components/schemas/DeleteRequest"
      responses:
        '200':
          description: Successful user deletion
          content:
            application/json:
              schema:
                $ref: "schemas.yaml#/components/schemas/DeleteResponse"
        '401':
          description: Invalid credentials
