/* tslint:disable */
/* eslint-disable */
/**
 * Authorization Resources
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Resource } from './Resource';
import {
    ResourceFromJSON,
    ResourceFromJSONTyped,
    ResourceToJSON,
    ResourceToJSONTyped,
} from './Resource';

/**
 * 
 * @export
 * @interface CreatedResource
 */
export interface CreatedResource {
    /**
     * 
     * @type {Resource}
     * @memberof CreatedResource
     */
    resource: Resource;
}

/**
 * Check if a given object implements the CreatedResource interface.
 */
export function instanceOfCreatedResource(value: object): value is CreatedResource {
    if (!('resource' in value) || value['resource'] === undefined) return false;
    return true;
}

export function CreatedResourceFromJSON(json: any): CreatedResource {
    return CreatedResourceFromJSONTyped(json, false);
}

export function CreatedResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatedResource {
    if (json == null) {
        return json;
    }
    return {
        
        'resource': ResourceFromJSON(json['resource']),
    };
}

export function CreatedResourceToJSON(json: any): CreatedResource {
    return CreatedResourceToJSONTyped(json, false);
}

export function CreatedResourceToJSONTyped(value?: CreatedResource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resource': ResourceToJSON(value['resource']),
    };
}

