/* tslint:disable */
/* eslint-disable */
/**
 * Authorization Resources
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Resource } from './Resource';
import {
    ResourceFromJSON,
    ResourceFromJSONTyped,
    ResourceToJSON,
    ResourceToJSONTyped,
} from './Resource';

/**
 * 
 * @export
 * @interface CreateResourceRequest
 */
export interface CreateResourceRequest {
    /**
     * 
     * @type {Resource}
     * @memberof CreateResourceRequest
     */
    resource: Resource;
}

/**
 * Check if a given object implements the CreateResourceRequest interface.
 */
export function instanceOfCreateResourceRequest(value: object): value is CreateResourceRequest {
    if (!('resource' in value) || value['resource'] === undefined) return false;
    return true;
}

export function CreateResourceRequestFromJSON(json: any): CreateResourceRequest {
    return CreateResourceRequestFromJSONTyped(json, false);
}

export function CreateResourceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateResourceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'resource': ResourceFromJSON(json['resource']),
    };
}

export function CreateResourceRequestToJSON(json: any): CreateResourceRequest {
    return CreateResourceRequestToJSONTyped(json, false);
}

export function CreateResourceRequestToJSONTyped(value?: CreateResourceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'resource': ResourceToJSON(value['resource']),
    };
}

