/* tslint:disable */
/* eslint-disable */
/**
 * Authorization Resources
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourceSearch
 */
export interface ResourceSearch {
    /**
     * 
     * @type {string}
     * @memberof ResourceSearch
     */
    group?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceSearch
     */
    kind?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceSearch
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ResourceSearch
     */
    query?: string;
}

/**
 * Check if a given object implements the ResourceSearch interface.
 */
export function instanceOfResourceSearch(value: object): value is ResourceSearch {
    return true;
}

export function ResourceSearchFromJSON(json: any): ResourceSearch {
    return ResourceSearchFromJSONTyped(json, false);
}

export function ResourceSearchFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceSearch {
    if (json == null) {
        return json;
    }
    return {
        
        'group': json['group'] == null ? undefined : json['group'],
        'kind': json['kind'] == null ? undefined : json['kind'],
        'name': json['name'] == null ? undefined : json['name'],
        'query': json['query'] == null ? undefined : json['query'],
    };
}

export function ResourceSearchToJSON(json: any): ResourceSearch {
    return ResourceSearchToJSONTyped(json, false);
}

export function ResourceSearchToJSONTyped(value?: ResourceSearch | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'group': value['group'],
        'kind': value['kind'],
        'name': value['name'],
        'query': value['query'],
    };
}

