/* tslint:disable */
/* eslint-disable */
/**
 * Authorization Resources
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Resource } from './Resource';
import {
    ResourceFromJSON,
    ResourceFromJSONTyped,
    ResourceToJSON,
    ResourceToJSONTyped,
} from './Resource';

/**
 * 
 * @export
 * @interface ResourceList
 */
export interface ResourceList {
    /**
     * 
     * @type {Array<Resource>}
     * @memberof ResourceList
     */
    items: Array<Resource>;
    /**
     * 
     * @type {number}
     * @memberof ResourceList
     */
    totalCount: number;
}

/**
 * Check if a given object implements the ResourceList interface.
 */
export function instanceOfResourceList(value: object): value is ResourceList {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    return true;
}

export function ResourceListFromJSON(json: any): ResourceList {
    return ResourceListFromJSONTyped(json, false);
}

export function ResourceListFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceList {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ResourceFromJSON)),
        'totalCount': json['total_count'],
    };
}

export function ResourceListToJSON(json: any): ResourceList {
    return ResourceListToJSONTyped(json, false);
}

export function ResourceListToJSONTyped(value?: ResourceList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(ResourceToJSON)),
        'total_count': value['totalCount'],
    };
}

