/* tslint:disable */
/* eslint-disable */
/**
 * Authorization Resources
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateResourceRequest
 */
export interface UpdateResourceRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateResourceRequest
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateResourceRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateResourceRequest
     */
    group?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateResourceRequest
     */
    kind?: string;
}

/**
 * Check if a given object implements the UpdateResourceRequest interface.
 */
export function instanceOfUpdateResourceRequest(value: object): value is UpdateResourceRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function UpdateResourceRequestFromJSON(json: any): UpdateResourceRequest {
    return UpdateResourceRequestFromJSONTyped(json, false);
}

export function UpdateResourceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateResourceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'group': json['group'] == null ? undefined : json['group'],
        'kind': json['kind'] == null ? undefined : json['kind'],
    };
}

export function UpdateResourceRequestToJSON(json: any): UpdateResourceRequest {
    return UpdateResourceRequestToJSONTyped(json, false);
}

export function UpdateResourceRequestToJSONTyped(value?: UpdateResourceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'group': value['group'],
        'kind': value['kind'],
    };
}

