// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permissions.query.sql

package datagen

import (
	"context"

	"github.com/google/uuid"
)

const createPermission = `-- name: CreatePermission :one
INSERT INTO permissionsv1 (
  name,
  "group",
  kind,
  actions,
  created_at,
  updated_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  now(),
  now()
) RETURNING id, name, "group", kind, actions, created_at, updated_at
`

type CreatePermissionParams struct {
	Name    string
	Group   string
	Kind    string
	Actions string
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permissionsv1, error) {
	row := q.db.QueryRow(ctx, createPermission,
		arg.Name,
		arg.Group,
		arg.Kind,
		arg.Actions,
	)
	var i Permissionsv1
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Group,
		&i.Kind,
		&i.Actions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePermission = `-- name: DeletePermission :exec
DELETE FROM permissionsv1 WHERE name = $1 AND "group" = $2 AND kind = $3
`

type DeletePermissionParams struct {
	Name  string
	Group string
	Kind  string
}

func (q *Queries) DeletePermission(ctx context.Context, arg DeletePermissionParams) error {
	_, err := q.db.Exec(ctx, deletePermission, arg.Name, arg.Group, arg.Kind)
	return err
}

const getPermission = `-- name: GetPermission :one
SELECT id, name, "group", kind, actions, created_at, updated_at FROM permissionsv1 WHERE name = $1 AND "group" = $2 AND kind = $3
`

type GetPermissionParams struct {
	Name  string
	Group string
	Kind  string
}

func (q *Queries) GetPermission(ctx context.Context, arg GetPermissionParams) (Permissionsv1, error) {
	row := q.db.QueryRow(ctx, getPermission, arg.Name, arg.Group, arg.Kind)
	var i Permissionsv1
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Group,
		&i.Kind,
		&i.Actions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPermissions = `-- name: GetPermissions :many
SELECT id, name, "group", kind, actions, created_at, updated_at FROM permissionsv1 ORDER BY name LIMIT $1 OFFSET $2
`

type GetPermissionsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetPermissions(ctx context.Context, arg GetPermissionsParams) ([]Permissionsv1, error) {
	rows, err := q.db.Query(ctx, getPermissions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permissionsv1
	for rows.Next() {
		var i Permissionsv1
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Group,
			&i.Kind,
			&i.Actions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermissionsForUser = `-- name: GetPermissionsForUser :many
SELECT
  p.id        AS permission_id,
  p.name      AS permission_name,
  p."group"   AS permission_group,
  p.kind      AS permission_kind,
  p.actions   AS actions
FROM rolebindingsv1 rb
INNER JOIN permissionbindingsv1 pb ON rb.role_id = pb.role_id
INNER JOIN permissionsv1 p ON pb.permission_id = p.id
WHERE rb.user_id = $1
  AND (p."group" = $2 OR p."group" = '*')
  AND (p.kind    = $3 OR p.kind    = '*')
`

type GetPermissionsForUserParams struct {
	UserID uuid.UUID
	Group  string
	Kind   string
}

type GetPermissionsForUserRow struct {
	PermissionID    uuid.UUID
	PermissionName  string
	PermissionGroup string
	PermissionKind  string
	Actions         string
}

func (q *Queries) GetPermissionsForUser(ctx context.Context, arg GetPermissionsForUserParams) ([]GetPermissionsForUserRow, error) {
	rows, err := q.db.Query(ctx, getPermissionsForUser, arg.UserID, arg.Group, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPermissionsForUserRow
	for rows.Next() {
		var i GetPermissionsForUserRow
		if err := rows.Scan(
			&i.PermissionID,
			&i.PermissionName,
			&i.PermissionGroup,
			&i.PermissionKind,
			&i.Actions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPermissionsForUserByGroup = `-- name: GetPermissionsForUserByGroup :many
SELECT
  p.id        AS permission_id,
  p.name      AS permission_name,
  p."group"   AS permission_group,
  p.kind      AS permission_kind,
  p.actions   AS actions
FROM rolebindingsv1 rb
INNER JOIN permissionbindingsv1 pb ON rb.role_id = pb.role_id
INNER JOIN permissionsv1 p ON pb.permission_id = p.id
WHERE rb.user_id = $1
  AND (p."group" = $2 OR p."group" = '*')
`

type GetPermissionsForUserByGroupParams struct {
	UserID uuid.UUID
	Group  string
}

type GetPermissionsForUserByGroupRow struct {
	PermissionID    uuid.UUID
	PermissionName  string
	PermissionGroup string
	PermissionKind  string
	Actions         string
}

func (q *Queries) GetPermissionsForUserByGroup(ctx context.Context, arg GetPermissionsForUserByGroupParams) ([]GetPermissionsForUserByGroupRow, error) {
	rows, err := q.db.Query(ctx, getPermissionsForUserByGroup, arg.UserID, arg.Group)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPermissionsForUserByGroupRow
	for rows.Next() {
		var i GetPermissionsForUserByGroupRow
		if err := rows.Scan(
			&i.PermissionID,
			&i.PermissionName,
			&i.PermissionGroup,
			&i.PermissionKind,
			&i.Actions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasPermission = `-- name: HasPermission :one
SELECT EXISTS (
  SELECT 1
  FROM rolebindingsv1 rb
  INNER JOIN permissionbindingsv1 pb ON rb.role_id = pb.role_id
  INNER JOIN permissionsv1 p ON pb.permission_id = p.id
  WHERE rb.user_id = $1
    AND (p.name    = $2 OR p.name    = '*')
    AND (p."group" = $3 OR p."group" = '*')
    AND (p.kind    = $4 OR p.kind    = '*')
    AND (
      p.actions = '*'
      OR p.actions = $5
      OR p.actions LIKE $5 || ',%'
      OR p.actions LIKE '%,' || $5
      OR p.actions LIKE '%,' || $5 || ',%'
    )
) AS has_permission
`

type HasPermissionParams struct {
	UserID  uuid.UUID
	Name    string
	Group   string
	Kind    string
	Actions string
}

func (q *Queries) HasPermission(ctx context.Context, arg HasPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPermission,
		arg.UserID,
		arg.Name,
		arg.Group,
		arg.Kind,
		arg.Actions,
	)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}
