// Code generated by MockGen. DO NOT EDIT.
// Source: reader.go
//
// Generated by this command:
//
//	mockgen -source=reader.go -destination=mocks/mock_reader.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	aggsv1 "github.com/ooqls/go-auth/internal/aggsv1"
	gomock "go.uber.org/mock/gomock"
)

// MockReader is a mock of Reader interface.
type MockReader struct {
	ctrl     *gomock.Controller
	recorder *MockReaderMockRecorder
	isgomock struct{}
}

// MockReaderMockRecorder is the mock recorder for MockReader.
type MockReaderMockRecorder struct {
	mock *MockReader
}

// NewMockReader creates a new mock instance.
func NewMockReader(ctrl *gomock.Controller) *MockReader {
	mock := &MockReader{ctrl: ctrl}
	mock.recorder = &MockReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReader) EXPECT() *MockReaderMockRecorder {
	return m.recorder
}

// CompareUserHierarchy mocks base method.
func (m *MockReader) CompareUserHierarchy(ctx context.Context, userA, userB uuid.UUID) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompareUserHierarchy", ctx, userA, userB)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CompareUserHierarchy indicates an expected call of CompareUserHierarchy.
func (mr *MockReaderMockRecorder) CompareUserHierarchy(ctx, userA, userB any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompareUserHierarchy", reflect.TypeOf((*MockReader)(nil).CompareUserHierarchy), ctx, userA, userB)
}

// GetRoleAgg mocks base method.
func (m *MockReader) GetRoleAgg(ctx context.Context, roleID uuid.UUID) (*aggsv1.RoleAgg, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleAgg", ctx, roleID)
	ret0, _ := ret[0].(*aggsv1.RoleAgg)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleAgg indicates an expected call of GetRoleAgg.
func (mr *MockReaderMockRecorder) GetRoleAgg(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleAgg", reflect.TypeOf((*MockReader)(nil).GetRoleAgg), ctx, roleID)
}

// GetUserAgg mocks base method.
func (m *MockReader) GetUserAgg(ctx context.Context, userID uuid.UUID) (*aggsv1.UserAgg, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAgg", ctx, userID)
	ret0, _ := ret[0].(*aggsv1.UserAgg)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAgg indicates an expected call of GetUserAgg.
func (mr *MockReaderMockRecorder) GetUserAgg(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAgg", reflect.TypeOf((*MockReader)(nil).GetUserAgg), ctx, userID)
}

// GetUserHierarchy mocks base method.
func (m *MockReader) GetUserHierarchy(ctx context.Context, userID uuid.UUID) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserHierarchy", ctx, userID)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserHierarchy indicates an expected call of GetUserHierarchy.
func (mr *MockReaderMockRecorder) GetUserHierarchy(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserHierarchy", reflect.TypeOf((*MockReader)(nil).GetUserHierarchy), ctx, userID)
}
