/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI specification for auth
 * This is the OpenAPI specification for the auth service.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticateRequest
 */
export interface AuthenticateRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthenticateRequest
     */
    token: string;
}

/**
 * Check if a given object implements the AuthenticateRequest interface.
 */
export function instanceOfAuthenticateRequest(value: object): value is AuthenticateRequest {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function AuthenticateRequestFromJSON(json: any): AuthenticateRequest {
    return AuthenticateRequestFromJSONTyped(json, false);
}

export function AuthenticateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function AuthenticateRequestToJSON(json: any): AuthenticateRequest {
    return AuthenticateRequestToJSONTyped(json, false);
}

export function AuthenticateRequestToJSONTyped(value?: AuthenticateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

