/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI specification for auth
 * This is the OpenAPI specification for the auth service.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticateResponse
 */
export interface AuthenticateResponse {
    /**
     * 
     * @type {string}
     * @memberof AuthenticateResponse
     */
    userId: string;
}

/**
 * Check if a given object implements the AuthenticateResponse interface.
 */
export function instanceOfAuthenticateResponse(value: object): value is AuthenticateResponse {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function AuthenticateResponseFromJSON(json: any): AuthenticateResponse {
    return AuthenticateResponseFromJSONTyped(json, false);
}

export function AuthenticateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
    };
}

export function AuthenticateResponseToJSON(json: any): AuthenticateResponse {
    return AuthenticateResponseToJSONTyped(json, false);
}

export function AuthenticateResponseToJSONTyped(value?: AuthenticateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
    };
}

