/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI specification for auth
 * This is the OpenAPI specification for the auth service.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChallengeClientResponse
 */
export interface ChallengeClientResponse {
    /**
     * 
     * @type {string}
     * @memberof ChallengeClientResponse
     */
    challenge: string;
    /**
     * 
     * @type {string}
     * @memberof ChallengeClientResponse
     */
    id: string;
}

/**
 * Check if a given object implements the ChallengeClientResponse interface.
 */
export function instanceOfChallengeClientResponse(value: object): value is ChallengeClientResponse {
    if (!('challenge' in value) || value['challenge'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ChallengeClientResponseFromJSON(json: any): ChallengeClientResponse {
    return ChallengeClientResponseFromJSONTyped(json, false);
}

export function ChallengeClientResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChallengeClientResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'challenge': json['challenge'],
        'id': json['id'],
    };
}

export function ChallengeClientResponseToJSON(json: any): ChallengeClientResponse {
    return ChallengeClientResponseToJSONTyped(json, false);
}

export function ChallengeClientResponseToJSONTyped(value?: ChallengeClientResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'challenge': value['challenge'],
        'id': value['id'],
    };
}

