/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI specification for auth
 * This is the OpenAPI specification for the auth service.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefreshResponse
 */
export interface RefreshResponse {
    /**
     * 
     * @type {string}
     * @memberof RefreshResponse
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof RefreshResponse
     */
    authToken: string;
}

/**
 * Check if a given object implements the RefreshResponse interface.
 */
export function instanceOfRefreshResponse(value: object): value is RefreshResponse {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('authToken' in value) || value['authToken'] === undefined) return false;
    return true;
}

export function RefreshResponseFromJSON(json: any): RefreshResponse {
    return RefreshResponseFromJSONTyped(json, false);
}

export function RefreshResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'authToken': json['auth_token'],
    };
}

export function RefreshResponseToJSON(json: any): RefreshResponse {
    return RefreshResponseToJSONTyped(json, false);
}

export function RefreshResponseToJSONTyped(value?: RefreshResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
        'auth_token': value['authToken'],
    };
}

