/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI specification for auth
 * This is the OpenAPI specification for the auth service.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegistrationResponse
 */
export interface RegistrationResponse {
    /**
     * 
     * @type {string}
     * @memberof RegistrationResponse
     */
    id: string;
}

/**
 * Check if a given object implements the RegistrationResponse interface.
 */
export function instanceOfRegistrationResponse(value: object): value is RegistrationResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function RegistrationResponseFromJSON(json: any): RegistrationResponse {
    return RegistrationResponseFromJSONTyped(json, false);
}

export function RegistrationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistrationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function RegistrationResponseToJSON(json: any): RegistrationResponse {
    return RegistrationResponseToJSONTyped(json, false);
}

export function RegistrationResponseToJSONTyped(value?: RegistrationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

