/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI specification for auth
 * This is the OpenAPI specification for the auth service.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegistrationRequest
 */
export interface RegistrationRequest {
    /**
     * 
     * @type {string}
     * @memberof RegistrationRequest
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationRequest
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationRequest
     */
    secret: string;
    /**
     * 
     * @type {string}
     * @memberof RegistrationRequest
     */
    email: string;
}

/**
 * Check if a given object implements the RegistrationRequest interface.
 */
export function instanceOfRegistrationRequest(value: object): value is RegistrationRequest {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('secret' in value) || value['secret'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function RegistrationRequestFromJSON(json: any): RegistrationRequest {
    return RegistrationRequestFromJSONTyped(json, false);
}

export function RegistrationRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistrationRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'key': json['key'],
        'secret': json['secret'],
        'email': json['email'],
    };
}

export function RegistrationRequestToJSON(json: any): RegistrationRequest {
    return RegistrationRequestToJSONTyped(json, false);
}

export function RegistrationRequestToJSONTyped(value?: RegistrationRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'key': value['key'],
        'secret': value['secret'],
        'email': value['email'],
    };
}

