/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI specification for auth
 * This is the OpenAPI specification for the auth service.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VerifyKeyRequest
 */
export interface VerifyKeyRequest {
    /**
     * 
     * @type {string}
     * @memberof VerifyKeyRequest
     */
    key: string;
}

/**
 * Check if a given object implements the VerifyKeyRequest interface.
 */
export function instanceOfVerifyKeyRequest(value: object): value is VerifyKeyRequest {
    if (!('key' in value) || value['key'] === undefined) return false;
    return true;
}

export function VerifyKeyRequestFromJSON(json: any): VerifyKeyRequest {
    return VerifyKeyRequestFromJSONTyped(json, false);
}

export function VerifyKeyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyKeyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
    };
}

export function VerifyKeyRequestToJSON(json: any): VerifyKeyRequest {
    return VerifyKeyRequestToJSONTyped(json, false);
}

export function VerifyKeyRequestToJSONTyped(value?: VerifyKeyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
    };
}

