// Code generated by MockGen. DO NOT EDIT.
// Source: reader.go
//
// Generated by this command:
//
//	mockgen -source=reader.go -destination=mocks/mock_reader.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	contexts "github.com/ooqls/go-auth/internal/contexts"
	corev1 "github.com/ooqls/go-auth/internal/corev1"
	permissionsv1 "github.com/ooqls/go-auth/internal/permissionsv1"
	gomock "go.uber.org/mock/gomock"
)

// MockReader is a mock of Reader interface.
type MockReader struct {
	ctrl     *gomock.Controller
	recorder *MockReaderMockRecorder
	isgomock struct{}
}

// MockReaderMockRecorder is the mock recorder for MockReader.
type MockReaderMockRecorder struct {
	mock *MockReader
}

// NewMockReader creates a new mock instance.
func NewMockReader(ctrl *gomock.Controller) *MockReader {
	mock := &MockReader{ctrl: ctrl}
	mock.recorder = &MockReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReader) EXPECT() *MockReaderMockRecorder {
	return m.recorder
}

// ClearCache mocks base method.
func (m *MockReader) ClearCache(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearCache", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearCache indicates an expected call of ClearCache.
func (mr *MockReaderMockRecorder) ClearCache(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearCache", reflect.TypeOf((*MockReader)(nil).ClearCache), ctx)
}

// GetPermission mocks base method.
func (m *MockReader) GetPermission(ctx contexts.LContext, permission string) (*permissionsv1.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermission", ctx, permission)
	ret0, _ := ret[0].(*permissionsv1.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermission indicates an expected call of GetPermission.
func (mr *MockReaderMockRecorder) GetPermission(ctx, permission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermission", reflect.TypeOf((*MockReader)(nil).GetPermission), ctx, permission)
}

// GetPermissions mocks base method.
func (m *MockReader) GetPermissions(ctx contexts.LContext, page, pageSize int) (*corev1.Result[[]permissionsv1.Permission], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermissions", ctx, page, pageSize)
	ret0, _ := ret[0].(*corev1.Result[[]permissionsv1.Permission])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermissions indicates an expected call of GetPermissions.
func (mr *MockReaderMockRecorder) GetPermissions(ctx, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissions", reflect.TypeOf((*MockReader)(nil).GetPermissions), ctx, page, pageSize)
}

// GetPermissionsForUser mocks base method.
func (m *MockReader) GetPermissionsForUser(ctx contexts.LContext, userID uuid.UUID) ([]permissionsv1.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermissionsForUser", ctx, userID)
	ret0, _ := ret[0].([]permissionsv1.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermissionsForUser indicates an expected call of GetPermissionsForUser.
func (mr *MockReaderMockRecorder) GetPermissionsForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissionsForUser", reflect.TypeOf((*MockReader)(nil).GetPermissionsForUser), ctx, userID)
}

// GetPermissionsForUserByGroup mocks base method.
func (m *MockReader) GetPermissionsForUserByGroup(ctx contexts.LContext, userID uuid.UUID) ([]permissionsv1.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermissionsForUserByGroup", ctx, userID)
	ret0, _ := ret[0].([]permissionsv1.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermissionsForUserByGroup indicates an expected call of GetPermissionsForUserByGroup.
func (mr *MockReaderMockRecorder) GetPermissionsForUserByGroup(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissionsForUserByGroup", reflect.TypeOf((*MockReader)(nil).GetPermissionsForUserByGroup), ctx, userID)
}

// HasCorePermission mocks base method.
func (m *MockReader) HasCorePermission(ctx contexts.LContext, userID uuid.UUID, group, kind, action string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasCorePermission", ctx, userID, group, kind, action)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasCorePermission indicates an expected call of HasCorePermission.
func (mr *MockReaderMockRecorder) HasCorePermission(ctx, userID, group, kind, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasCorePermission", reflect.TypeOf((*MockReader)(nil).HasCorePermission), ctx, userID, group, kind, action)
}

// HasResourcePermission mocks base method.
func (m *MockReader) HasResourcePermission(ctx contexts.LContext, userID uuid.UUID, group, kind, action string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasResourcePermission", ctx, userID, group, kind, action)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasResourcePermission indicates an expected call of HasResourcePermission.
func (mr *MockReaderMockRecorder) HasResourcePermission(ctx, userID, group, kind, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasResourcePermission", reflect.TypeOf((*MockReader)(nil).HasResourcePermission), ctx, userID, group, kind, action)
}

// SearchPermissions mocks base method.
func (m *MockReader) SearchPermissions(ctx contexts.LContext, permission string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchPermissions", ctx, permission)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchPermissions indicates an expected call of SearchPermissions.
func (mr *MockReaderMockRecorder) SearchPermissions(ctx, permission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchPermissions", reflect.TypeOf((*MockReader)(nil).SearchPermissions), ctx, permission)
}
