// Code generated by MockGen. DO NOT EDIT.
// Source: writer.go
//
// Generated by this command:
//
//	mockgen -source=writer.go -destination=mocks/mock_writer.go -package=mocks -mock_names=Writer=MockWriter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	challengeattempts "github.com/ooqls/go-auth/internal/challenge_attempts"
	gomock "go.uber.org/mock/gomock"
)

// MockWriter is a mock of Writer interface.
type MockWriter struct {
	ctrl     *gomock.Controller
	recorder *MockWriterMockRecorder
	isgomock struct{}
}

// MockWriterMockRecorder is the mock recorder for MockWriter.
type MockWriterMockRecorder struct {
	mock *MockWriter
}

// NewMockWriter creates a new mock instance.
func NewMockWriter(ctrl *gomock.Controller) *MockWriter {
	mock := &MockWriter{ctrl: ctrl}
	mock.recorder = &MockWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWriter) EXPECT() *MockWriterMockRecorder {
	return m.recorder
}

// CreateChallengeAttempt mocks base method.
func (m *MockWriter) CreateChallengeAttempt(ctx context.Context, challengeAttempt challengeattempts.ChallengeAttempt) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateChallengeAttempt", ctx, challengeAttempt)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateChallengeAttempt indicates an expected call of CreateChallengeAttempt.
func (mr *MockWriterMockRecorder) CreateChallengeAttempt(ctx, challengeAttempt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateChallengeAttempt", reflect.TypeOf((*MockWriter)(nil).CreateChallengeAttempt), ctx, challengeAttempt)
}
