/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI specification for auth
 * This is the OpenAPI specification for the auth service.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssignPermissionRequest
 */
export interface AssignPermissionRequest {
    /**
     * 
     * @type {string}
     * @memberof AssignPermissionRequest
     */
    roleId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AssignPermissionRequest
     */
    permissions?: Array<string>;
}

/**
 * Check if a given object implements the AssignPermissionRequest interface.
 */
export function instanceOfAssignPermissionRequest(value: object): value is AssignPermissionRequest {
    return true;
}

export function AssignPermissionRequestFromJSON(json: any): AssignPermissionRequest {
    return AssignPermissionRequestFromJSONTyped(json, false);
}

export function AssignPermissionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssignPermissionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'roleId': json['role_id'] == null ? undefined : json['role_id'],
        'permissions': json['permissions'] == null ? undefined : json['permissions'],
    };
}

export function AssignPermissionRequestToJSON(json: any): AssignPermissionRequest {
    return AssignPermissionRequestToJSONTyped(json, false);
}

export function AssignPermissionRequestToJSONTyped(value?: AssignPermissionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'role_id': value['roleId'],
        'permissions': value['permissions'],
    };
}

