/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI specification for auth
 * This is the OpenAPI specification for the auth service.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RoleBindingRequest
 */
export interface RoleBindingRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof RoleBindingRequest
     */
    assignRoleIds?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof RoleBindingRequest
     */
    unassignRoleIds?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RoleBindingRequest
     */
    userId?: string;
}

/**
 * Check if a given object implements the RoleBindingRequest interface.
 */
export function instanceOfRoleBindingRequest(value: object): value is RoleBindingRequest {
    return true;
}

export function RoleBindingRequestFromJSON(json: any): RoleBindingRequest {
    return RoleBindingRequestFromJSONTyped(json, false);
}

export function RoleBindingRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleBindingRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'assignRoleIds': json['assign_role_ids'] == null ? undefined : json['assign_role_ids'],
        'unassignRoleIds': json['unassign_role_ids'] == null ? undefined : json['unassign_role_ids'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function RoleBindingRequestToJSON(json: any): RoleBindingRequest {
    return RoleBindingRequestToJSONTyped(json, false);
}

export function RoleBindingRequestToJSONTyped(value?: RoleBindingRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assign_role_ids': value['assignRoleIds'],
        'unassign_role_ids': value['unassignRoleIds'],
        'user_id': value['userId'],
    };
}

