/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI specification for auth
 * This is the OpenAPI specification for the auth service.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateRoleRequest
 */
export interface UpdateRoleRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateRoleRequest
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateRoleRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateRoleRequest
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateRoleRequest
     */
    hierarchy?: number;
}

/**
 * Check if a given object implements the UpdateRoleRequest interface.
 */
export function instanceOfUpdateRoleRequest(value: object): value is UpdateRoleRequest {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function UpdateRoleRequestFromJSON(json: any): UpdateRoleRequest {
    return UpdateRoleRequestFromJSONTyped(json, false);
}

export function UpdateRoleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRoleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'hierarchy': json['hierarchy'] == null ? undefined : json['hierarchy'],
    };
}

export function UpdateRoleRequestToJSON(json: any): UpdateRoleRequest {
    return UpdateRoleRequestToJSONTyped(json, false);
}

export function UpdateRoleRequestToJSONTyped(value?: UpdateRoleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'hierarchy': value['hierarchy'],
    };
}

