// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: aggs.query.sql

package datagen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const compareUserRoleHierarchy = `-- name: CompareUserRoleHierarchy :one
SELECT SIGN(actor.hierarchy - target.hierarchy)::int
FROM user_highest_role actor
JOIN user_highest_role target ON target.user_id = $2
WHERE actor.user_id = $1
`

type CompareUserRoleHierarchyParams struct {
	UserID   uuid.UUID
	UserID_2 uuid.UUID
}

func (q *Queries) CompareUserRoleHierarchy(ctx context.Context, arg CompareUserRoleHierarchyParams) (int32, error) {
	row := q.db.QueryRow(ctx, compareUserRoleHierarchy, arg.UserID, arg.UserID_2)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getRoleAggregate = `-- name: GetRoleAggregate :many
SELECT
  r.id          AS role_id,
  r.name        AS role_name,
  r.hierarchy   AS hierarchy,
  r.description AS description,
  r.created_at  AS role_created_at,
  r.updated_at  AS role_updated_at,
  p.id          AS permission_id,
  p.name        AS permission_name,
  p."group"     AS permission_group,
  p.kind        AS permission_kind,
  p.actions     AS actions,
  p.created_at  AS permission_created_at,
  p.updated_at  AS permission_updated_at
FROM rolesv1 r
INNER JOIN permissionbindingsv1 pb ON r.id = pb.role_id
INNER JOIN permissionsv1 p ON pb.permission_id = p.id
WHERE r.id = $1
`

type GetRoleAggregateRow struct {
	RoleID              uuid.UUID
	RoleName            string
	Hierarchy           int32
	Description         string
	RoleCreatedAt       pgtype.Timestamptz
	RoleUpdatedAt       pgtype.Timestamptz
	PermissionID        uuid.UUID
	PermissionName      string
	PermissionGroup     string
	PermissionKind      string
	Actions             string
	PermissionCreatedAt pgtype.Timestamptz
	PermissionUpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetRoleAggregate(ctx context.Context, id uuid.UUID) ([]GetRoleAggregateRow, error) {
	rows, err := q.db.Query(ctx, getRoleAggregate, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoleAggregateRow
	for rows.Next() {
		var i GetRoleAggregateRow
		if err := rows.Scan(
			&i.RoleID,
			&i.RoleName,
			&i.Hierarchy,
			&i.Description,
			&i.RoleCreatedAt,
			&i.RoleUpdatedAt,
			&i.PermissionID,
			&i.PermissionName,
			&i.PermissionGroup,
			&i.PermissionKind,
			&i.Actions,
			&i.PermissionCreatedAt,
			&i.PermissionUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAggregate = `-- name: GetUserAggregate :many
SELECT
  u.id          AS user_id,
  u.username    AS username,
  u.email       AS email,
  u.created_at  AS user_created_at,
  u.updated_at  AS user_updated_at,
  r.id          AS role_id,
  r.name        AS role_name,
  r.hierarchy   AS hierarchy,
  r.description AS role_description,
  r.created_at  AS role_created_at,
  r.updated_at  AS role_updated_at,
  p.id          AS permission_id,
  p.name        AS permission_name,
  p."group"     AS permission_group,
  p.kind        AS permission_kind,
  p.actions     AS actions,
  p.created_at  AS permission_created_at,
  p.updated_at  AS permission_updated_at
FROM usersv1 u
LEFT JOIN rolebindingsv1 rb ON u.id = rb.user_id
LEFT JOIN rolesv1 r ON rb.role_id = r.id
LEFT JOIN permissionbindingsv1 pb ON r.id = pb.role_id
LEFT JOIN permissionsv1 p ON pb.permission_id = p.id
WHERE u.id = $1
`

type GetUserAggregateRow struct {
	UserID              uuid.UUID
	Username            string
	Email               string
	UserCreatedAt       pgtype.Timestamptz
	UserUpdatedAt       pgtype.Timestamptz
	RoleID              pgtype.UUID
	RoleName            pgtype.Text
	Hierarchy           pgtype.Int4
	RoleDescription     pgtype.Text
	RoleCreatedAt       pgtype.Timestamptz
	RoleUpdatedAt       pgtype.Timestamptz
	PermissionID        pgtype.UUID
	PermissionName      pgtype.Text
	PermissionGroup     pgtype.Text
	PermissionKind      pgtype.Text
	Actions             pgtype.Text
	PermissionCreatedAt pgtype.Timestamptz
	PermissionUpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetUserAggregate(ctx context.Context, id uuid.UUID) ([]GetUserAggregateRow, error) {
	rows, err := q.db.Query(ctx, getUserAggregate, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserAggregateRow
	for rows.Next() {
		var i GetUserAggregateRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Email,
			&i.UserCreatedAt,
			&i.UserUpdatedAt,
			&i.RoleID,
			&i.RoleName,
			&i.Hierarchy,
			&i.RoleDescription,
			&i.RoleCreatedAt,
			&i.RoleUpdatedAt,
			&i.PermissionID,
			&i.PermissionName,
			&i.PermissionGroup,
			&i.PermissionKind,
			&i.Actions,
			&i.PermissionCreatedAt,
			&i.PermissionUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserHierarchy = `-- name: GetUserHierarchy :one
SELECT hierarchy FROM user_highest_role WHERE user_id = $1
`

func (q *Queries) GetUserHierarchy(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getUserHierarchy, userID)
	var hierarchy int32
	err := row.Scan(&hierarchy)
	return hierarchy, err
}
