// Code generated by MockGen. DO NOT EDIT.
// Source: reader.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	resourcesv1 "github.com/ooqls/go-auth/internal/resourcesv1"
)

// MockReader is a mock of Reader interface.
type MockReader struct {
	ctrl     *gomock.Controller
	recorder *MockReaderMockRecorder
}

// MockReaderMockRecorder is the mock recorder for MockReader.
type MockReaderMockRecorder struct {
	mock *MockReader
}

// NewMockReader creates a new mock instance.
func NewMockReader(ctrl *gomock.Controller) *MockReader {
	mock := &MockReader{ctrl: ctrl}
	mock.recorder = &MockReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReader) EXPECT() *MockReaderMockRecorder {
	return m.recorder
}

// ClearCache mocks base method.
func (m *MockReader) ClearCache(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearCache", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearCache indicates an expected call of ClearCache.
func (mr *MockReaderMockRecorder) ClearCache(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearCache", reflect.TypeOf((*MockReader)(nil).ClearCache), ctx)
}

// GetResource mocks base method.
func (m *MockReader) GetResource(ctx context.Context, group, kind, name string) (*resourcesv1.Resourcev1, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResource", ctx, group, kind, name)
	ret0, _ := ret[0].(*resourcesv1.Resourcev1)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResource indicates an expected call of GetResource.
func (mr *MockReaderMockRecorder) GetResource(ctx, group, kind, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResource", reflect.TypeOf((*MockReader)(nil).GetResource), ctx, group, kind, name)
}

// GetResourceByID mocks base method.
func (m *MockReader) GetResourceByID(ctx context.Context, id uuid.UUID) (*resourcesv1.Resourcev1, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResourceByID", ctx, id)
	ret0, _ := ret[0].(*resourcesv1.Resourcev1)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResourceByID indicates an expected call of GetResourceByID.
func (mr *MockReaderMockRecorder) GetResourceByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResourceByID", reflect.TypeOf((*MockReader)(nil).GetResourceByID), ctx, id)
}

// GetResources mocks base method.
func (m *MockReader) GetResources(ctx context.Context, limit, offset int32) ([]resourcesv1.Resourcev1, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResources", ctx, limit, offset)
	ret0, _ := ret[0].([]resourcesv1.Resourcev1)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResources indicates an expected call of GetResources.
func (mr *MockReaderMockRecorder) GetResources(ctx, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResources", reflect.TypeOf((*MockReader)(nil).GetResources), ctx, limit, offset)
}

// GetResourcesByGroup mocks base method.
func (m *MockReader) GetResourcesByGroup(ctx context.Context, group string, limit, offset int32) ([]resourcesv1.Resourcev1, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResourcesByGroup", ctx, group, limit, offset)
	ret0, _ := ret[0].([]resourcesv1.Resourcev1)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResourcesByGroup indicates an expected call of GetResourcesByGroup.
func (mr *MockReaderMockRecorder) GetResourcesByGroup(ctx, group, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResourcesByGroup", reflect.TypeOf((*MockReader)(nil).GetResourcesByGroup), ctx, group, limit, offset)
}

// GetResourcesByGroupAndKind mocks base method.
func (m *MockReader) GetResourcesByGroupAndKind(ctx context.Context, group, kind string, limit, offset int32) ([]resourcesv1.Resourcev1, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResourcesByGroupAndKind", ctx, group, kind, limit, offset)
	ret0, _ := ret[0].([]resourcesv1.Resourcev1)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResourcesByGroupAndKind indicates an expected call of GetResourcesByGroupAndKind.
func (mr *MockReaderMockRecorder) GetResourcesByGroupAndKind(ctx, group, kind, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResourcesByGroupAndKind", reflect.TypeOf((*MockReader)(nil).GetResourcesByGroupAndKind), ctx, group, kind, limit, offset)
}
