name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the auth
      run: make build_auth
    - name: login to docker hub
      run: echo "${{ secrets.DOCKER_REGISTRY_TOKEN }}" | docker login -u samrreynolds4 --password-stdin
    - name: push the auth
      run: make push_auth
