// Package gen_roles provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package gen_roles

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
	externalRef0 "github.com/ooqls/go-auth/v1/gen"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// AssignPermissionRequest defines model for AssignPermissionRequest.
type AssignPermissionRequest struct {
	Permissions *[]string           `json:"permissions,omitempty"`
	RoleId      *openapi_types.UUID `json:"role_id,omitempty"`
}

// CreateRoleRequest defines model for CreateRoleRequest.
type CreateRoleRequest struct {
	Description string   `json:"description"`
	Hierarchy   int      `json:"hierarchy"`
	Name        string   `json:"name"`
	Permissions []string `json:"permissions"`
}

// CreateRoleResponse defines model for CreateRoleResponse.
type CreateRoleResponse struct {
	Id openapi_types.UUID `json:"id"`
}

// RoleBindingRequest defines model for RoleBindingRequest.
type RoleBindingRequest struct {
	AssignRoleIds   *[]openapi_types.UUID `json:"assign_role_ids,omitempty"`
	UnassignRoleIds *[]openapi_types.UUID `json:"unassign_role_ids,omitempty"`
	UserId          *openapi_types.UUID   `json:"user_id,omitempty"`
}

// RolesList defines model for RolesList.
type RolesList struct {
	Items      []externalRef0.Role `json:"items"`
	TotalCount int                 `json:"total_count"`
}

// UnassignPermissionRequest defines model for UnassignPermissionRequest.
type UnassignPermissionRequest struct {
	Permissions *[]string           `json:"permissions,omitempty"`
	RoleId      *openapi_types.UUID `json:"role_id,omitempty"`
}

// UpdateRoleRequest defines model for UpdateRoleRequest.
type UpdateRoleRequest struct {
	Description *string            `json:"description,omitempty"`
	Hierarchy   *int               `json:"hierarchy,omitempty"`
	Id          openapi_types.UUID `json:"id"`
	Name        *string            `json:"name,omitempty"`
}

// GetAuthRolesParams defines parameters for GetAuthRoles.
type GetAuthRolesParams struct {
	// Page The page number
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// PageSize The page size
	PageSize *int `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// DeleteAuthRoleJSONRequestBody defines body for DeleteAuthRole for application/json ContentType.
type DeleteAuthRoleJSONRequestBody = externalRef0.DeleteRequest

// CreateAuthRoleJSONRequestBody defines body for CreateAuthRole for application/json ContentType.
type CreateAuthRoleJSONRequestBody = CreateRoleRequest

// UpdateAuthRoleJSONRequestBody defines body for UpdateAuthRole for application/json ContentType.
type UpdateAuthRoleJSONRequestBody = UpdateRoleRequest

// UpdateRoleBindingsJSONRequestBody defines body for UpdateRoleBindings for application/json ContentType.
type UpdateRoleBindingsJSONRequestBody = RoleBindingRequest

// UnassignRolePermissionsJSONRequestBody defines body for UnassignRolePermissions for application/json ContentType.
type UnassignRolePermissionsJSONRequestBody = UnassignPermissionRequest

// AssignRolePermissionsJSONRequestBody defines body for AssignRolePermissions for application/json ContentType.
type AssignRolePermissionsJSONRequestBody = AssignPermissionRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// DeleteAuthRoleWithBody request with any body
	DeleteAuthRoleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	DeleteAuthRole(ctx context.Context, body DeleteAuthRoleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateAuthRoleWithBody request with any body
	CreateAuthRoleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateAuthRole(ctx context.Context, body CreateAuthRoleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateAuthRoleWithBody request with any body
	UpdateAuthRoleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateAuthRole(ctx context.Context, body UpdateAuthRoleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateRoleBindingsWithBody request with any body
	UpdateRoleBindingsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateRoleBindings(ctx context.Context, body UpdateRoleBindingsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UnassignRolePermissionsWithBody request with any body
	UnassignRolePermissionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UnassignRolePermissions(ctx context.Context, body UnassignRolePermissionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AssignRolePermissionsWithBody request with any body
	AssignRolePermissionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	AssignRolePermissions(ctx context.Context, body AssignRolePermissionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAuthRole request
	GetAuthRole(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAuthRoles request
	GetAuthRoles(ctx context.Context, params *GetAuthRolesParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) DeleteAuthRoleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteAuthRoleRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteAuthRole(ctx context.Context, body DeleteAuthRoleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteAuthRoleRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateAuthRoleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateAuthRoleRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateAuthRole(ctx context.Context, body CreateAuthRoleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateAuthRoleRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateAuthRoleWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateAuthRoleRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateAuthRole(ctx context.Context, body UpdateAuthRoleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateAuthRoleRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateRoleBindingsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateRoleBindingsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateRoleBindings(ctx context.Context, body UpdateRoleBindingsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateRoleBindingsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UnassignRolePermissionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUnassignRolePermissionsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UnassignRolePermissions(ctx context.Context, body UnassignRolePermissionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUnassignRolePermissionsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AssignRolePermissionsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAssignRolePermissionsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) AssignRolePermissions(ctx context.Context, body AssignRolePermissionsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAssignRolePermissionsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAuthRole(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAuthRoleRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetAuthRoles(ctx context.Context, params *GetAuthRolesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAuthRolesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewDeleteAuthRoleRequest calls the generic DeleteAuthRole builder with application/json body
func NewDeleteAuthRoleRequest(server string, body DeleteAuthRoleJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewDeleteAuthRoleRequestWithBody(server, "application/json", bodyReader)
}

// NewDeleteAuthRoleRequestWithBody generates requests for DeleteAuthRole with any type of body
func NewDeleteAuthRoleRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/role")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateAuthRoleRequest calls the generic CreateAuthRole builder with application/json body
func NewCreateAuthRoleRequest(server string, body CreateAuthRoleJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateAuthRoleRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateAuthRoleRequestWithBody generates requests for CreateAuthRole with any type of body
func NewCreateAuthRoleRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/role")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewUpdateAuthRoleRequest calls the generic UpdateAuthRole builder with application/json body
func NewUpdateAuthRoleRequest(server string, body UpdateAuthRoleJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateAuthRoleRequestWithBody(server, "application/json", bodyReader)
}

// NewUpdateAuthRoleRequestWithBody generates requests for UpdateAuthRole with any type of body
func NewUpdateAuthRoleRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/role")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewUpdateRoleBindingsRequest calls the generic UpdateRoleBindings builder with application/json body
func NewUpdateRoleBindingsRequest(server string, body UpdateRoleBindingsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateRoleBindingsRequestWithBody(server, "application/json", bodyReader)
}

// NewUpdateRoleBindingsRequestWithBody generates requests for UpdateRoleBindings with any type of body
func NewUpdateRoleBindingsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/role/binding")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewUnassignRolePermissionsRequest calls the generic UnassignRolePermissions builder with application/json body
func NewUnassignRolePermissionsRequest(server string, body UnassignRolePermissionsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUnassignRolePermissionsRequestWithBody(server, "application/json", bodyReader)
}

// NewUnassignRolePermissionsRequestWithBody generates requests for UnassignRolePermissions with any type of body
func NewUnassignRolePermissionsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/role/permissions")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewAssignRolePermissionsRequest calls the generic AssignRolePermissions builder with application/json body
func NewAssignRolePermissionsRequest(server string, body AssignRolePermissionsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAssignRolePermissionsRequestWithBody(server, "application/json", bodyReader)
}

// NewAssignRolePermissionsRequestWithBody generates requests for AssignRolePermissions with any type of body
func NewAssignRolePermissionsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/role/permissions")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetAuthRoleRequest generates requests for GetAuthRole
func NewGetAuthRoleRequest(server string, id openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/role/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAuthRolesRequest generates requests for GetAuthRoles
func NewGetAuthRolesRequest(server string, params *GetAuthRolesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/roles")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page", runtime.ParamLocationQuery, *params.Page); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "page_size", runtime.ParamLocationQuery, *params.PageSize); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// DeleteAuthRoleWithBodyWithResponse request with any body
	DeleteAuthRoleWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeleteAuthRoleResponse, error)

	DeleteAuthRoleWithResponse(ctx context.Context, body DeleteAuthRoleJSONRequestBody, reqEditors ...RequestEditorFn) (*DeleteAuthRoleResponse, error)

	// CreateAuthRoleWithBodyWithResponse request with any body
	CreateAuthRoleWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateAuthRoleResponse, error)

	CreateAuthRoleWithResponse(ctx context.Context, body CreateAuthRoleJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateAuthRoleResponse, error)

	// UpdateAuthRoleWithBodyWithResponse request with any body
	UpdateAuthRoleWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateAuthRoleResponse, error)

	UpdateAuthRoleWithResponse(ctx context.Context, body UpdateAuthRoleJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateAuthRoleResponse, error)

	// UpdateRoleBindingsWithBodyWithResponse request with any body
	UpdateRoleBindingsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateRoleBindingsResponse, error)

	UpdateRoleBindingsWithResponse(ctx context.Context, body UpdateRoleBindingsJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateRoleBindingsResponse, error)

	// UnassignRolePermissionsWithBodyWithResponse request with any body
	UnassignRolePermissionsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UnassignRolePermissionsResponse, error)

	UnassignRolePermissionsWithResponse(ctx context.Context, body UnassignRolePermissionsJSONRequestBody, reqEditors ...RequestEditorFn) (*UnassignRolePermissionsResponse, error)

	// AssignRolePermissionsWithBodyWithResponse request with any body
	AssignRolePermissionsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AssignRolePermissionsResponse, error)

	AssignRolePermissionsWithResponse(ctx context.Context, body AssignRolePermissionsJSONRequestBody, reqEditors ...RequestEditorFn) (*AssignRolePermissionsResponse, error)

	// GetAuthRoleWithResponse request
	GetAuthRoleWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetAuthRoleResponse, error)

	// GetAuthRolesWithResponse request
	GetAuthRolesWithResponse(ctx context.Context, params *GetAuthRolesParams, reqEditors ...RequestEditorFn) (*GetAuthRolesResponse, error)
}

type DeleteAuthRoleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *externalRef0.DeleteResponse
}

// Status returns HTTPResponse.Status
func (r DeleteAuthRoleResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteAuthRoleResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateAuthRoleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CreateRoleResponse
}

// Status returns HTTPResponse.Status
func (r CreateAuthRoleResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateAuthRoleResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateAuthRoleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *externalRef0.Role
}

// Status returns HTTPResponse.Status
func (r UpdateAuthRoleResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateAuthRoleResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateRoleBindingsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r UpdateRoleBindingsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateRoleBindingsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UnassignRolePermissionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *externalRef0.Role
}

// Status returns HTTPResponse.Status
func (r UnassignRolePermissionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UnassignRolePermissionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type AssignRolePermissionsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *externalRef0.Role
}

// Status returns HTTPResponse.Status
func (r AssignRolePermissionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AssignRolePermissionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAuthRoleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *externalRef0.Role
}

// Status returns HTTPResponse.Status
func (r GetAuthRoleResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAuthRoleResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetAuthRolesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RolesList
}

// Status returns HTTPResponse.Status
func (r GetAuthRolesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAuthRolesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// DeleteAuthRoleWithBodyWithResponse request with arbitrary body returning *DeleteAuthRoleResponse
func (c *ClientWithResponses) DeleteAuthRoleWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DeleteAuthRoleResponse, error) {
	rsp, err := c.DeleteAuthRoleWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteAuthRoleResponse(rsp)
}

func (c *ClientWithResponses) DeleteAuthRoleWithResponse(ctx context.Context, body DeleteAuthRoleJSONRequestBody, reqEditors ...RequestEditorFn) (*DeleteAuthRoleResponse, error) {
	rsp, err := c.DeleteAuthRole(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteAuthRoleResponse(rsp)
}

// CreateAuthRoleWithBodyWithResponse request with arbitrary body returning *CreateAuthRoleResponse
func (c *ClientWithResponses) CreateAuthRoleWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateAuthRoleResponse, error) {
	rsp, err := c.CreateAuthRoleWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateAuthRoleResponse(rsp)
}

func (c *ClientWithResponses) CreateAuthRoleWithResponse(ctx context.Context, body CreateAuthRoleJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateAuthRoleResponse, error) {
	rsp, err := c.CreateAuthRole(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateAuthRoleResponse(rsp)
}

// UpdateAuthRoleWithBodyWithResponse request with arbitrary body returning *UpdateAuthRoleResponse
func (c *ClientWithResponses) UpdateAuthRoleWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateAuthRoleResponse, error) {
	rsp, err := c.UpdateAuthRoleWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateAuthRoleResponse(rsp)
}

func (c *ClientWithResponses) UpdateAuthRoleWithResponse(ctx context.Context, body UpdateAuthRoleJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateAuthRoleResponse, error) {
	rsp, err := c.UpdateAuthRole(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateAuthRoleResponse(rsp)
}

// UpdateRoleBindingsWithBodyWithResponse request with arbitrary body returning *UpdateRoleBindingsResponse
func (c *ClientWithResponses) UpdateRoleBindingsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateRoleBindingsResponse, error) {
	rsp, err := c.UpdateRoleBindingsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateRoleBindingsResponse(rsp)
}

func (c *ClientWithResponses) UpdateRoleBindingsWithResponse(ctx context.Context, body UpdateRoleBindingsJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateRoleBindingsResponse, error) {
	rsp, err := c.UpdateRoleBindings(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateRoleBindingsResponse(rsp)
}

// UnassignRolePermissionsWithBodyWithResponse request with arbitrary body returning *UnassignRolePermissionsResponse
func (c *ClientWithResponses) UnassignRolePermissionsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UnassignRolePermissionsResponse, error) {
	rsp, err := c.UnassignRolePermissionsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUnassignRolePermissionsResponse(rsp)
}

func (c *ClientWithResponses) UnassignRolePermissionsWithResponse(ctx context.Context, body UnassignRolePermissionsJSONRequestBody, reqEditors ...RequestEditorFn) (*UnassignRolePermissionsResponse, error) {
	rsp, err := c.UnassignRolePermissions(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUnassignRolePermissionsResponse(rsp)
}

// AssignRolePermissionsWithBodyWithResponse request with arbitrary body returning *AssignRolePermissionsResponse
func (c *ClientWithResponses) AssignRolePermissionsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AssignRolePermissionsResponse, error) {
	rsp, err := c.AssignRolePermissionsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAssignRolePermissionsResponse(rsp)
}

func (c *ClientWithResponses) AssignRolePermissionsWithResponse(ctx context.Context, body AssignRolePermissionsJSONRequestBody, reqEditors ...RequestEditorFn) (*AssignRolePermissionsResponse, error) {
	rsp, err := c.AssignRolePermissions(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAssignRolePermissionsResponse(rsp)
}

// GetAuthRoleWithResponse request returning *GetAuthRoleResponse
func (c *ClientWithResponses) GetAuthRoleWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetAuthRoleResponse, error) {
	rsp, err := c.GetAuthRole(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAuthRoleResponse(rsp)
}

// GetAuthRolesWithResponse request returning *GetAuthRolesResponse
func (c *ClientWithResponses) GetAuthRolesWithResponse(ctx context.Context, params *GetAuthRolesParams, reqEditors ...RequestEditorFn) (*GetAuthRolesResponse, error) {
	rsp, err := c.GetAuthRoles(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAuthRolesResponse(rsp)
}

// ParseDeleteAuthRoleResponse parses an HTTP response from a DeleteAuthRoleWithResponse call
func ParseDeleteAuthRoleResponse(rsp *http.Response) (*DeleteAuthRoleResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteAuthRoleResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest externalRef0.DeleteResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateAuthRoleResponse parses an HTTP response from a CreateAuthRoleWithResponse call
func ParseCreateAuthRoleResponse(rsp *http.Response) (*CreateAuthRoleResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateAuthRoleResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CreateRoleResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseUpdateAuthRoleResponse parses an HTTP response from a UpdateAuthRoleWithResponse call
func ParseUpdateAuthRoleResponse(rsp *http.Response) (*UpdateAuthRoleResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateAuthRoleResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest externalRef0.Role
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseUpdateRoleBindingsResponse parses an HTTP response from a UpdateRoleBindingsWithResponse call
func ParseUpdateRoleBindingsResponse(rsp *http.Response) (*UpdateRoleBindingsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateRoleBindingsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseUnassignRolePermissionsResponse parses an HTTP response from a UnassignRolePermissionsWithResponse call
func ParseUnassignRolePermissionsResponse(rsp *http.Response) (*UnassignRolePermissionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UnassignRolePermissionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest externalRef0.Role
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseAssignRolePermissionsResponse parses an HTTP response from a AssignRolePermissionsWithResponse call
func ParseAssignRolePermissionsResponse(rsp *http.Response) (*AssignRolePermissionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AssignRolePermissionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest externalRef0.Role
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetAuthRoleResponse parses an HTTP response from a GetAuthRoleWithResponse call
func ParseGetAuthRoleResponse(rsp *http.Response) (*GetAuthRoleResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAuthRoleResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest externalRef0.Role
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetAuthRolesResponse parses an HTTP response from a GetAuthRolesWithResponse call
func ParseGetAuthRolesResponse(rsp *http.Response) (*GetAuthRolesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAuthRolesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RolesList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (DELETE /role)
	DeleteAuthRole(c *gin.Context)

	// (POST /role)
	CreateAuthRole(c *gin.Context)

	// (PUT /role)
	UpdateAuthRole(c *gin.Context)

	// (POST /role/binding)
	UpdateRoleBindings(c *gin.Context)

	// (DELETE /role/permissions)
	UnassignRolePermissions(c *gin.Context)

	// (POST /role/permissions)
	AssignRolePermissions(c *gin.Context)

	// (GET /role/{id})
	GetAuthRole(c *gin.Context, id openapi_types.UUID)
	// Get all roles
	// (GET /roles)
	GetAuthRoles(c *gin.Context, params GetAuthRolesParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// DeleteAuthRole operation middleware
func (siw *ServerInterfaceWrapper) DeleteAuthRole(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteAuthRole(c)
}

// CreateAuthRole operation middleware
func (siw *ServerInterfaceWrapper) CreateAuthRole(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateAuthRole(c)
}

// UpdateAuthRole operation middleware
func (siw *ServerInterfaceWrapper) UpdateAuthRole(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateAuthRole(c)
}

// UpdateRoleBindings operation middleware
func (siw *ServerInterfaceWrapper) UpdateRoleBindings(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateRoleBindings(c)
}

// UnassignRolePermissions operation middleware
func (siw *ServerInterfaceWrapper) UnassignRolePermissions(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UnassignRolePermissions(c)
}

// AssignRolePermissions operation middleware
func (siw *ServerInterfaceWrapper) AssignRolePermissions(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AssignRolePermissions(c)
}

// GetAuthRole operation middleware
func (siw *ServerInterfaceWrapper) GetAuthRole(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAuthRole(c, id)
}

// GetAuthRoles operation middleware
func (siw *ServerInterfaceWrapper) GetAuthRoles(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAuthRolesParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page_size" -------------

	err = runtime.BindQueryParameter("form", true, false, "page_size", c.Request.URL.Query(), &params.PageSize)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page_size: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAuthRoles(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.DELETE(options.BaseURL+"/role", wrapper.DeleteAuthRole)
	router.POST(options.BaseURL+"/role", wrapper.CreateAuthRole)
	router.PUT(options.BaseURL+"/role", wrapper.UpdateAuthRole)
	router.POST(options.BaseURL+"/role/binding", wrapper.UpdateRoleBindings)
	router.DELETE(options.BaseURL+"/role/permissions", wrapper.UnassignRolePermissions)
	router.POST(options.BaseURL+"/role/permissions", wrapper.AssignRolePermissions)
	router.GET(options.BaseURL+"/role/:id", wrapper.GetAuthRole)
	router.GET(options.BaseURL+"/roles", wrapper.GetAuthRoles)
}
